// src/contexts/LanguageContext.tsx
// Taal context voor NL/EN wisselaar

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'nl' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// ─── Vertalingen ─────────────────────────────────────────────────────

const translations: Record<Language, Record<string, string>> = {
  nl: {
    // Navigation
    'nav.overview': 'Overzicht',
    'nav.settings': 'Instellingen',
    'nav.intelligence': 'Intelligentie',
    'nav.campaigns': 'Campagnes',
    'nav.automation': 'Automatisering',
    'nav.analytics': 'Analyse',
    'nav.search': 'Zoeken',
    'nav.profile': 'Profiel',
    'nav.orgAdmin': 'Org Admin',
    'nav.adminPortal': 'Admin Portal',
    'nav.helpCenter': 'Helpcentrum',
    'nav.signOut': 'Uitloggen',
    'nav.website': 'Website',
    'nav.proPlan': 'Pro Plan',
    'nav.home': 'Home',

    // Nav sub-items
    'nav.brandSetup': 'Merk Setup',
    'nav.targetAudience': 'Doelgroep',
    'nav.goals': 'Doelen & KPIs',
    'nav.competition': 'Concurrentie',
    'nav.growthBlueprint': 'Groei Blauwdruk',
    'nav.growthBlueprintDesc': 'Complete bedrijfsanalyse in 60 seconden',
    'nav.marketingScanner': 'Marketing Scanner',
    'nav.marketingScannerDesc': 'AI-gestuurde merk- & marktanalyse',
    'nav.brandMemory': 'Merkgeheugen',
    'nav.marketInsights': 'Marktinzichten',
    'nav.competitorAnalysis': 'Concurrentieanalyse',
    'nav.contentStudio': 'Content Studio',
    'nav.campaignManagement': 'Campagne Beheer',
    'nav.emailMarketing': 'E-mail Marketing',
    'nav.socialMedia': 'Social Media',
    'nav.landingPages': 'Landingspagina\'s',
    'nav.workflows': 'Workflows',
    'nav.customerJourney': 'Klantreis',
    'nav.aiAgents': 'AI Agents',
    'nav.smartTriggers': 'Slimme Triggers',

    // Dashboard
    'dashboard.title': 'Executive Dashboard',
    'dashboard.noCampaigns': 'Nog geen actieve campagnes — maak er een om te beginnen',
    'dashboard.refresh': 'Vernieuwen',
    'dashboard.thisMonth': 'Deze Maand',
    'dashboard.filter': 'Filter',
    'dashboard.exportReport': 'Rapport Exporteren',
    'dashboard.newReport': 'Nieuw Rapport',
    'dashboard.overview': 'Overzicht',
    'dashboard.performance': 'Prestaties',
    'dashboard.analyticsTab': 'Analytics',
    'dashboard.intelligenceTab': 'Intelligentie',
    'dashboard.totalBudget': 'Totaal Budget',
    'dashboard.activeCampaigns': 'Actieve Campagnes',
    'dashboard.totalContacts': 'Totale Contacten',
    'dashboard.totalCampaigns': 'Totale Campagnes',
    'dashboard.campaignProgress': 'Campagne Voortgang',
    'dashboard.campaignProgressDesc': 'Overzicht van je marketing campagnes',
    'dashboard.noCampaignsYet': 'Nog geen campagnes. Maak je eerste campagne om voortgang te zien.',
    'dashboard.aiInsights': 'AI-Gedreven Inzichten',
    'dashboard.aiInsightsDesc': 'Intelligentie uit je marketing data',
    'dashboard.campaignStatus': 'Campagne Status',
    'dashboard.contactGrowth': 'Contact Groei',
    'dashboard.budgetUtilization': 'Budget Benutting',
    'dashboard.networkError': 'Netwerk Fout',
    'dashboard.networkErrorDesc': 'Zorg ervoor dat de backend draait op localhost:8000 en dat je bent ingelogd.',
    'dashboard.retry': 'Opnieuw',

    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fout',
    'common.save': 'Opslaan',
    'common.cancel': 'Annuleren',
    'common.delete': 'Verwijderen',
    'common.edit': 'Bewerken',
    'common.create': 'Aanmaken',
    'common.search': 'Zoeken',
    'common.noResults': 'Geen resultaten',
    'common.back': 'Terug',
    'common.next': 'Volgende',
    'common.close': 'Sluiten',
    'common.confirm': 'Bevestigen',
    'common.active': 'Actief',
    'common.inactive': 'Inactief',
    'common.draft': 'Concept',
    'common.inDatabase': 'In je database',
    'common.across': 'Over',

    // Copilot
    'copilot.title': 'AI Copilot',
    'copilot.online': 'Online',
    'copilot.placeholder': 'Stel een vraag...',
    'copilot.thinking': 'Aan het nadenken...',
    'copilot.hello': 'Hallo! Ik ben uw AI Copilot',
    'copilot.helloDesc': 'Ik help u met marketing strategie, content & inzichten',
    'copilot.suggestions': 'Suggesties',
    'copilot.quickActions': 'Snelle Acties',
    'copilot.footer': 'Inclufy AI Copilot · Powered by gespecialiseerde agents',

    // Settings / Profile page
    'settings.title': 'Instellingen',
    'settings.subtitle': 'Beheer je accountinstellingen en voorkeuren',
    'settings.tab.profile': 'Profiel',
    'settings.tab.security': 'Beveiliging',
    'settings.tab.preferences': 'Voorkeuren',
    'settings.tab.apiKeys': 'API Keys',

    // Profile tab
    'settings.profile.title': 'Profielinformatie',
    'settings.profile.subtitle': 'Werk je persoonlijke gegevens bij',
    'settings.profile.firstName': 'Voornaam',
    'settings.profile.lastName': 'Achternaam',
    'settings.profile.email': 'E-mail',
    'settings.profile.emailHint': 'E-mailadres kan niet worden gewijzigd',
    'settings.profile.role': 'Rol',
    'settings.profile.phone': 'Telefoon',
    'settings.profile.company': 'Bedrijf',
    'settings.profile.bio': 'Bio',
    'settings.profile.bioPlaceholder': 'Vertel iets over jezelf...',
    'settings.profile.saveChanges': 'Wijzigingen Opslaan',
    'settings.profile.saved': 'Profiel bijgewerkt',
    'settings.profile.avatar': 'Profielfoto',
    'settings.profile.changeAvatar': 'Foto Wijzigen',
    'settings.profile.memberSince': 'Lid sinds',

    // Security tab
    'settings.security.title': 'Beveiliging',
    'settings.security.subtitle': 'Beheer je wachtwoord en beveiligingsinstellingen',
    'settings.security.currentPassword': 'Huidig Wachtwoord',
    'settings.security.newPassword': 'Nieuw Wachtwoord',
    'settings.security.confirmPassword': 'Bevestig Wachtwoord',
    'settings.security.updatePassword': 'Wachtwoord Bijwerken',
    'settings.security.passwordUpdated': 'Wachtwoord bijgewerkt',
    'settings.security.twoFactor': 'Twee-factor Authenticatie',
    'settings.security.twoFactorDesc': 'Voeg een extra beveiligingslaag toe aan je account',
    'settings.security.enable2FA': '2FA Inschakelen',
    'settings.security.disable2FA': '2FA Uitschakelen',
    'settings.security.mfaEnabled': '2FA is ingeschakeld',
    'settings.security.mfaDisabled': '2FA is uitgeschakeld',
    'settings.security.mfaEnabledDesc': 'Je account is beschermd met twee-factor authenticatie',
    'settings.security.mfaDisabledDesc': 'Schakel 2FA in voor extra beveiliging',
    'settings.security.scanQR': 'Scan deze QR-code met je authenticator app',
    'settings.security.secretKey': 'Of voer deze code handmatig in',
    'settings.security.enterCode': 'Voer de 6-cijferige code in uit je authenticator app',
    'settings.security.verifyAndEnable': 'Verifieer & Activeer',
    'settings.security.mfaSuccess': '2FA succesvol ingeschakeld!',
    'settings.security.mfaRemoved': '2FA is uitgeschakeld',
    'settings.security.mfaError': 'Fout bij 2FA instellen',
    'settings.security.mfaInvalidCode': 'Ongeldige code. Probeer opnieuw.',
    'settings.security.mfaConfirmDisable': 'Weet je zeker dat je 2FA wilt uitschakelen?',
    'settings.security.cancel': 'Annuleren',
    'settings.security.copied': 'Gekopieerd!',
    'login.mfa.title': 'Twee-factor Authenticatie',
    'login.mfa.subtitle': 'Voer de 6-cijferige code in uit je authenticator app',
    'login.mfa.verify': 'Verifiëren',
    'login.mfa.invalid': 'Ongeldige code. Probeer opnieuw.',
    'login.mfa.error': 'Verificatie mislukt',
    'settings.security.sessions': 'Actieve Sessies',
    'settings.security.sessionsDesc': 'Beheer je ingelogde apparaten',
    'settings.security.currentSession': 'Huidige Sessie',
    'settings.security.revokeAll': 'Alle Sessies Beëindigen',
    'settings.security.lastActive': 'Laatst Actief',

    // Preferences tab
    'settings.preferences.title': 'Voorkeuren',
    'settings.preferences.subtitle': 'Pas je werkruimte en notificatie-instellingen aan',
    'settings.preferences.language': 'Taal',
    'settings.preferences.languageDesc': 'Kies je voorkeurstaal',
    'settings.preferences.theme': 'Thema',
    'settings.preferences.themeDesc': 'Kies licht of donker thema',
    'settings.preferences.light': 'Licht',
    'settings.preferences.dark': 'Donker',
    'settings.preferences.system': 'Systeem',
    'settings.preferences.notifications': 'Meldingen',
    'settings.preferences.emailNotifications': 'E-mail Meldingen',
    'settings.preferences.emailNotificationsDesc': 'Ontvang e-mail updates over je campagnes',
    'settings.preferences.campaignAlerts': 'Campagne Meldingen',
    'settings.preferences.campaignAlertsDesc': 'Ontvang een melding wanneer campagnes zijn voltooid',
    'settings.preferences.weeklyReport': 'Wekelijks Rapport',
    'settings.preferences.weeklyReportDesc': 'Ontvang een wekelijks overzicht van je prestaties',
    'settings.preferences.saved': 'Voorkeuren opgeslagen',

    // API Keys tab
    'settings.apiKeys.title': 'API Keys',
    'settings.apiKeys.subtitle': 'Beheer API-sleutels voor integraties',
    'settings.apiKeys.createKey': 'Nieuwe API Key',
    'settings.apiKeys.name': 'Naam',
    'settings.apiKeys.key': 'Sleutel',
    'settings.apiKeys.created': 'Aangemaakt',
    'settings.apiKeys.lastUsed': 'Laatst Gebruikt',
    'settings.apiKeys.status': 'Status',
    'settings.apiKeys.revoke': 'Intrekken',
    'settings.apiKeys.noKeys': 'Nog geen API keys. Maak je eerste key aan.',
    'settings.apiKeys.serverSide': 'Server-side',
    'settings.apiKeys.openai': 'OpenAI',
    'settings.apiKeys.openaiDesc': 'AI-contentgeneratie',
    'settings.apiKeys.emailProvider': 'E-mail Provider',
    'settings.apiKeys.emailProviderDesc': 'SendGrid of Resend voor e-mailbezorging',
    'settings.apiKeys.stripe': 'Stripe',
    'settings.apiKeys.stripeDesc': 'Betalingsverwerking',
    'settings.apiKeys.supabase': 'Supabase',
    'settings.apiKeys.supabaseDesc': 'Database & authenticatie',

    // Onboarding
    'onboarding.title': 'Welkom bij Inclufy',
    'onboarding.step': 'Stap',
    'onboarding.of': 'van',
    'onboarding.next': 'Volgende',
    'onboarding.previous': 'Vorige',
    'onboarding.skip': 'Overslaan',
    'onboarding.finish': 'Aan de slag!',
    'onboarding.step1.title': 'Vertel ons over je bedrijf',
    'onboarding.step1.subtitle': 'We gebruiken deze informatie om je marketing te personaliseren',
    'onboarding.step1.companyName': 'Bedrijfsnaam',
    'onboarding.step1.website': 'Website URL',
    'onboarding.step1.tagline': 'Tagline / Slogan',
    'onboarding.step1.industry': 'Branche',
    'onboarding.step1.country': 'Land',
    'onboarding.step1.language': 'Taal',
    'onboarding.step2.title': 'AI Website Analyse',
    'onboarding.step2.subtitle': 'We analyseren je website om je marketing te optimaliseren',
    'onboarding.step2.scanning': 'Je website wordt geanalyseerd...',
    'onboarding.step2.complete': 'Analyse voltooid!',
    'onboarding.step2.score': 'Score',
    'onboarding.step2.seo': 'SEO',
    'onboarding.step2.content': 'Content',
    'onboarding.step2.performance': 'Prestatie',
    'onboarding.step3.title': 'Product of Dienst',
    'onboarding.step3.subtitle': 'Wat verkoopt je bedrijf?',
    'onboarding.step3.productName': 'Productnaam',
    'onboarding.step3.description': 'Korte beschrijving',
    'onboarding.step3.benefits': 'Belangrijkste voordelen',
    'onboarding.step4.title': 'Doelgroep',
    'onboarding.step4.subtitle': 'Wie wil je bedrijf bereiken?',
    'onboarding.step4.audienceType': 'Type klant',
    'onboarding.step4.idealCustomer': 'Ideale Klant',
    'onboarding.step4.customerSector': 'Sector van klanten',
    'onboarding.step4.companySize': 'Bedrijfsgrootte',
    'onboarding.step4.ageGroup': 'Leeftijdsgroep',
    'onboarding.step4.occupation': 'Beroep / Rol',
    'onboarding.step4.painPoints': 'Pijnpunten',
    'onboarding.step5.title': 'Marketingdoelen',
    'onboarding.step5.subtitle': 'Wat wil je bereiken met marketing?',
    'onboarding.step6.title': 'Merkprofiel',
    'onboarding.step6.subtitle': 'Definieer je merkidentiteit',
    'onboarding.step6.primaryColor': 'Primaire kleur',
    'onboarding.step6.secondaryColor': 'Secundaire kleur',
    'onboarding.step6.tone': 'Merkstijl',
    'onboarding.step6.brandValues': 'Merkwaarden',
    'onboarding.step6.mission': 'Missie',
    'onboarding.step6.messagingDos': 'Wel zeggen',
    'onboarding.step6.messagingDonts': 'Niet zeggen',
    'onboarding.step6.logo': 'Logo (optioneel)',
    'onboarding.step7.title': 'Concurrenten',
    'onboarding.step7.subtitle': 'AI vindt SEO-kansen en content gaps',
    'onboarding.step8.title': 'Portfolio / Bestaande Content',
    'onboarding.step8.subtitle': 'Laat AI leren van je bestaande stijl',
    'onboarding.step9.title': 'Je bent klaar!',
    'onboarding.step9.subtitle': 'Overzicht van je instellingen',
    'onboarding.step9.startButton': 'Start AI Marketing',
    'onboarding.step9.goDashboard': 'Naar Dashboard',
    'onboarding.step9.goContent': 'Content Hub',
    'onboarding.step9.goSocial': 'Social Posts',

    // Content Hub
    'contentHub.title': 'Content Studio',
    'contentHub.subtitle': 'Creëer, beheer en publiceer je marketing content',
    'contentHub.aiWriter': 'AI Writer',
    'contentHub.aiWriterDesc': 'Blogs, artikelen, advertentieteksten',
    'contentHub.socialPosts': 'Social Posts',
    'contentHub.socialPostsDesc': 'Instagram, LinkedIn, Facebook, X',
    'contentHub.imageGen': 'Afbeeldingen',
    'contentHub.imageGenDesc': 'AI-gegenereerde visuals',
    'contentHub.videoCreator': 'Video Creator',
    'contentHub.videoCreatorDesc': 'Commercials met animatie & stem',
    'contentHub.emailCampaign': 'E-mail Campagnes',
    'contentHub.emailCampaignDesc': 'Nieuwsbrieven, follow-ups, promos',
    'contentHub.tutorialCreator': 'Tutorial Creator',
    'contentHub.tutorialCreatorDesc': 'Stap-voor-stap tutorials met video',
    'contentHub.recent': 'Recente Content',
    'contentHub.noContent': 'Nog geen content. Maak je eerste item!',
    'contentHub.viewAll': 'Bekijk Alles',
    'contentHub.stats': 'Statistieken',
    'contentHub.totalItems': 'Totaal Items',
  },

  en: {
    // Navigation
    'nav.overview': 'Overview',
    'nav.settings': 'Settings',
    'nav.intelligence': 'Intelligence',
    'nav.campaigns': 'Campaigns',
    'nav.automation': 'Automation',
    'nav.analytics': 'Analytics',
    'nav.search': 'Search',
    'nav.profile': 'Profile',
    'nav.orgAdmin': 'Org Admin',
    'nav.adminPortal': 'Admin Portal',
    'nav.helpCenter': 'Help Center',
    'nav.signOut': 'Sign Out',
    'nav.website': 'Website',
    'nav.proPlan': 'Pro Plan',
    'nav.home': 'Home',

    // Nav sub-items
    'nav.brandSetup': 'Brand Setup',
    'nav.targetAudience': 'Target Audience',
    'nav.goals': 'Goals & KPIs',
    'nav.competition': 'Competition',
    'nav.growthBlueprint': 'Growth Blueprint',
    'nav.growthBlueprintDesc': 'Complete business analysis in 60 seconds',
    'nav.marketingScanner': 'Marketing Scanner',
    'nav.marketingScannerDesc': 'AI-driven brand & market analysis',
    'nav.brandMemory': 'Brand Memory',
    'nav.marketInsights': 'Market Insights',
    'nav.competitorAnalysis': 'Competitor Analysis',
    'nav.contentStudio': 'Content Studio',
    'nav.campaignManagement': 'Campaign Management',
    'nav.emailMarketing': 'Email Marketing',
    'nav.socialMedia': 'Social Media',
    'nav.landingPages': 'Landing Pages',
    'nav.workflows': 'Workflows',
    'nav.customerJourney': 'Customer Journey',
    'nav.aiAgents': 'AI Agents',
    'nav.smartTriggers': 'Smart Triggers',

    // Dashboard
    'dashboard.title': 'Executive Dashboard',
    'dashboard.noCampaigns': 'No active campaigns yet — create one to get started',
    'dashboard.refresh': 'Refresh',
    'dashboard.thisMonth': 'This Month',
    'dashboard.filter': 'Filter',
    'dashboard.exportReport': 'Export Report',
    'dashboard.newReport': 'New Report',
    'dashboard.overview': 'Overview',
    'dashboard.performance': 'Performance',
    'dashboard.analyticsTab': 'Analytics',
    'dashboard.intelligenceTab': 'Intelligence',
    'dashboard.totalBudget': 'Total Budget',
    'dashboard.activeCampaigns': 'Active Campaigns',
    'dashboard.totalContacts': 'Total Contacts',
    'dashboard.totalCampaigns': 'Total Campaigns',
    'dashboard.campaignProgress': 'Campaign Progress',
    'dashboard.campaignProgressDesc': 'Overview of your marketing campaigns',
    'dashboard.noCampaignsYet': 'No campaigns yet. Create your first campaign to see progress.',
    'dashboard.aiInsights': 'AI-Powered Insights',
    'dashboard.aiInsightsDesc': 'Intelligence from your marketing data',
    'dashboard.campaignStatus': 'Campaign Status',
    'dashboard.contactGrowth': 'Contact Growth',
    'dashboard.budgetUtilization': 'Budget Utilization',
    'dashboard.networkError': 'Network Error',
    'dashboard.networkErrorDesc': 'Make sure the backend is running at localhost:8000 and you are logged in.',
    'dashboard.retry': 'Retry',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.noResults': 'No results',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.draft': 'Draft',
    'common.inDatabase': 'In your database',
    'common.across': 'Across',

    // Copilot
    'copilot.title': 'AI Copilot',
    'copilot.online': 'Online',
    'copilot.placeholder': 'Ask a question...',
    'copilot.thinking': 'Thinking...',
    'copilot.hello': 'Hello! I am your AI Copilot',
    'copilot.helloDesc': 'I help you with marketing strategy, content & insights',
    'copilot.suggestions': 'Suggestions',
    'copilot.quickActions': 'Quick Actions',
    'copilot.footer': 'Inclufy AI Copilot · Powered by specialized agents',

    // Settings / Profile page
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account settings and preferences',
    'settings.tab.profile': 'Profile',
    'settings.tab.security': 'Security',
    'settings.tab.preferences': 'Preferences',
    'settings.tab.apiKeys': 'API Keys',

    // Profile tab
    'settings.profile.title': 'Profile Information',
    'settings.profile.subtitle': 'Update your personal details',
    'settings.profile.firstName': 'First Name',
    'settings.profile.lastName': 'Last Name',
    'settings.profile.email': 'Email',
    'settings.profile.emailHint': 'Email address cannot be changed',
    'settings.profile.role': 'Role',
    'settings.profile.phone': 'Phone',
    'settings.profile.company': 'Company',
    'settings.profile.bio': 'Bio',
    'settings.profile.bioPlaceholder': 'Tell something about yourself...',
    'settings.profile.saveChanges': 'Save Changes',
    'settings.profile.saved': 'Profile updated',
    'settings.profile.avatar': 'Profile Photo',
    'settings.profile.changeAvatar': 'Change Photo',
    'settings.profile.memberSince': 'Member since',

    // Security tab
    'settings.security.title': 'Security',
    'settings.security.subtitle': 'Manage your password and security settings',
    'settings.security.currentPassword': 'Current Password',
    'settings.security.newPassword': 'New Password',
    'settings.security.confirmPassword': 'Confirm Password',
    'settings.security.updatePassword': 'Update Password',
    'settings.security.passwordUpdated': 'Password updated',
    'settings.security.twoFactor': 'Two-Factor Authentication',
    'settings.security.twoFactorDesc': 'Add an extra layer of security to your account',
    'settings.security.enable2FA': 'Enable 2FA',
    'settings.security.disable2FA': 'Disable 2FA',
    'settings.security.mfaEnabled': '2FA is enabled',
    'settings.security.mfaDisabled': '2FA is disabled',
    'settings.security.mfaEnabledDesc': 'Your account is protected with two-factor authentication',
    'settings.security.mfaDisabledDesc': 'Enable 2FA for extra security',
    'settings.security.scanQR': 'Scan this QR code with your authenticator app',
    'settings.security.secretKey': 'Or enter this code manually',
    'settings.security.enterCode': 'Enter the 6-digit code from your authenticator app',
    'settings.security.verifyAndEnable': 'Verify & Enable',
    'settings.security.mfaSuccess': '2FA enabled successfully!',
    'settings.security.mfaRemoved': '2FA has been disabled',
    'settings.security.mfaError': 'Error setting up 2FA',
    'settings.security.mfaInvalidCode': 'Invalid code. Please try again.',
    'settings.security.mfaConfirmDisable': 'Are you sure you want to disable 2FA?',
    'settings.security.cancel': 'Cancel',
    'settings.security.copied': 'Copied!',
    'login.mfa.title': 'Two-Factor Authentication',
    'login.mfa.subtitle': 'Enter the 6-digit code from your authenticator app',
    'login.mfa.verify': 'Verify',
    'login.mfa.invalid': 'Invalid code. Please try again.',
    'login.mfa.error': 'Verification failed',
    'settings.security.sessions': 'Active Sessions',
    'settings.security.sessionsDesc': 'Manage your logged-in devices',
    'settings.security.currentSession': 'Current Session',
    'settings.security.revokeAll': 'Revoke All Sessions',
    'settings.security.lastActive': 'Last Active',

    // Preferences tab
    'settings.preferences.title': 'Preferences',
    'settings.preferences.subtitle': 'Customize your workspace and notification settings',
    'settings.preferences.language': 'Language',
    'settings.preferences.languageDesc': 'Choose your preferred language',
    'settings.preferences.theme': 'Theme',
    'settings.preferences.themeDesc': 'Choose light or dark theme',
    'settings.preferences.light': 'Light',
    'settings.preferences.dark': 'Dark',
    'settings.preferences.system': 'System',
    'settings.preferences.notifications': 'Notifications',
    'settings.preferences.emailNotifications': 'Email Notifications',
    'settings.preferences.emailNotificationsDesc': 'Receive email updates about your campaigns',
    'settings.preferences.campaignAlerts': 'Campaign Alerts',
    'settings.preferences.campaignAlertsDesc': 'Get notified when campaigns are completed',
    'settings.preferences.weeklyReport': 'Weekly Report',
    'settings.preferences.weeklyReportDesc': 'Receive a weekly overview of your performance',
    'settings.preferences.saved': 'Preferences saved',

    // API Keys tab
    'settings.apiKeys.title': 'API Keys',
    'settings.apiKeys.subtitle': 'Manage API keys for integrations',
    'settings.apiKeys.createKey': 'New API Key',
    'settings.apiKeys.name': 'Name',
    'settings.apiKeys.key': 'Key',
    'settings.apiKeys.created': 'Created',
    'settings.apiKeys.lastUsed': 'Last Used',
    'settings.apiKeys.status': 'Status',
    'settings.apiKeys.revoke': 'Revoke',
    'settings.apiKeys.noKeys': 'No API keys yet. Create your first key.',
    'settings.apiKeys.serverSide': 'Server-side',
    'settings.apiKeys.openai': 'OpenAI',
    'settings.apiKeys.openaiDesc': 'AI content generation',
    'settings.apiKeys.emailProvider': 'Email Provider',
    'settings.apiKeys.emailProviderDesc': 'SendGrid or Resend for email delivery',
    'settings.apiKeys.stripe': 'Stripe',
    'settings.apiKeys.stripeDesc': 'Payment processing',
    'settings.apiKeys.supabase': 'Supabase',
    'settings.apiKeys.supabaseDesc': 'Database & authentication',

    // Onboarding
    'onboarding.title': 'Welcome to Inclufy',
    'onboarding.step': 'Step',
    'onboarding.of': 'of',
    'onboarding.next': 'Next',
    'onboarding.previous': 'Previous',
    'onboarding.skip': 'Skip',
    'onboarding.finish': 'Get Started!',
    'onboarding.step1.title': 'Tell us about your business',
    'onboarding.step1.subtitle': 'We use this information to personalize your marketing',
    'onboarding.step1.companyName': 'Company Name',
    'onboarding.step1.website': 'Website URL',
    'onboarding.step1.tagline': 'Tagline / Slogan',
    'onboarding.step1.industry': 'Industry',
    'onboarding.step1.country': 'Country',
    'onboarding.step1.language': 'Language',
    'onboarding.step2.title': 'AI Website Analysis',
    'onboarding.step2.subtitle': 'We analyze your website to optimize your marketing',
    'onboarding.step2.scanning': 'Analyzing your website...',
    'onboarding.step2.complete': 'Analysis complete!',
    'onboarding.step2.score': 'Score',
    'onboarding.step2.seo': 'SEO',
    'onboarding.step2.content': 'Content',
    'onboarding.step2.performance': 'Performance',
    'onboarding.step3.title': 'Product or Service',
    'onboarding.step3.subtitle': 'What does your company sell?',
    'onboarding.step3.productName': 'Product Name',
    'onboarding.step3.description': 'Short Description',
    'onboarding.step3.benefits': 'Key Benefits',
    'onboarding.step4.title': 'Target Audience',
    'onboarding.step4.subtitle': 'Who does your business want to reach?',
    'onboarding.step4.audienceType': 'Customer Type',
    'onboarding.step4.idealCustomer': 'Ideal Customer',
    'onboarding.step4.customerSector': 'Customer Sector',
    'onboarding.step4.companySize': 'Company Size',
    'onboarding.step4.ageGroup': 'Age Group',
    'onboarding.step4.occupation': 'Occupation / Role',
    'onboarding.step4.painPoints': 'Pain Points',
    'onboarding.step5.title': 'Marketing Goals',
    'onboarding.step5.subtitle': 'What do you want to achieve with marketing?',
    'onboarding.step6.title': 'Brand Profile',
    'onboarding.step6.subtitle': 'Define your brand identity',
    'onboarding.step6.primaryColor': 'Primary Color',
    'onboarding.step6.secondaryColor': 'Secondary Color',
    'onboarding.step6.tone': 'Brand Tone',
    'onboarding.step6.brandValues': 'Brand Values',
    'onboarding.step6.mission': 'Mission',
    'onboarding.step6.messagingDos': 'Do Say',
    'onboarding.step6.messagingDonts': "Don't Say",
    'onboarding.step6.logo': 'Logo (optional)',
    'onboarding.step7.title': 'Competitors',
    'onboarding.step7.subtitle': 'AI finds SEO opportunities and content gaps',
    'onboarding.step8.title': 'Portfolio / Existing Content',
    'onboarding.step8.subtitle': 'Let AI learn from your existing style',
    'onboarding.step9.title': "You're all set!",
    'onboarding.step9.subtitle': 'Overview of your settings',
    'onboarding.step9.startButton': 'Start AI Marketing',
    'onboarding.step9.goDashboard': 'Go to Dashboard',
    'onboarding.step9.goContent': 'Content Hub',
    'onboarding.step9.goSocial': 'Social Posts',

    // Content Hub
    'contentHub.title': 'Content Studio',
    'contentHub.subtitle': 'Create, manage and publish your marketing content',
    'contentHub.aiWriter': 'AI Writer',
    'contentHub.aiWriterDesc': 'Blogs, articles, ad copy',
    'contentHub.socialPosts': 'Social Posts',
    'contentHub.socialPostsDesc': 'Instagram, LinkedIn, Facebook, X',
    'contentHub.imageGen': 'Images',
    'contentHub.imageGenDesc': 'AI-generated visuals',
    'contentHub.videoCreator': 'Video Creator',
    'contentHub.videoCreatorDesc': 'Commercials with animation & voice',
    'contentHub.emailCampaign': 'Email Campaigns',
    'contentHub.emailCampaignDesc': 'Newsletters, follow-ups, promos',
    'contentHub.tutorialCreator': 'Tutorial Creator',
    'contentHub.tutorialCreatorDesc': 'Step-by-step tutorials with video',
    'contentHub.recent': 'Recent Content',
    'contentHub.noContent': 'No content yet. Create your first item!',
    'contentHub.viewAll': 'View All',
    'contentHub.stats': 'Statistics',
    'contentHub.totalItems': 'Total Items',
  },
};

// ─── Provider ────────────────────────────────────────────────────────

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('inclufy_lang');
    return (saved === 'en' || saved === 'nl') ? saved : 'nl';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('inclufy_lang', newLang);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations['nl']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    // Fallback: return NL defaults when outside provider
    return {
      lang: 'nl' as Language,
      setLang: () => {},
      t: (key: string) => translations['nl']?.[key] || key,
    };
  }
  return ctx;
}
