// src/services/demo-agent/templates/construction.template.ts
import type { IndustryTemplate } from '../types';
import { daysFromNow } from './base-template';

export const constructionTemplate: IndustryTemplate = {
  industry: 'construction',

  brand: {
    name: 'BuildRight Group',
    tagline: 'Building Tomorrow\'s Infrastructure Today',
    mission: 'To empower construction companies with intelligent project management software that delivers projects on time, on budget, and safely.',
    description: 'BuildRight Group is a leading construction technology company providing BIM-integrated project management, site safety monitoring, and cost estimation software for general contractors, infrastructure developers, and engineering firms across Europe.',
    tone_attributes: ['Practical', 'Reliable', 'Results-oriented', 'Safety-conscious'],
    primary_color: '#F59E0B',
    secondary_color: '#D97706',
    usps: ['BIM-native project management platform', 'Real-time site safety monitoring with IoT', '30% reduction in project cost overruns', 'Predictive scheduling with AI-driven risk analysis'],
    brand_values: ['Safety-first', 'Reliability', 'Innovation', 'Sustainability', 'Precision'],
    audiences: ['Project managers', 'Construction directors', 'General contractors', 'Site engineers'],
    industries: ['Construction', 'Civil engineering', 'Infrastructure', 'Real estate development'],
    messaging_dos: 'Use concrete data and project outcomes. Emphasize safety records and compliance. Reference industry standards (ISO 19650, BIM Level 2). Highlight ROI with measurable KPIs like schedule adherence and cost variance.',
    messaging_donts: 'Never understate safety risks. Avoid overpromising timelines. Do not use jargon without context for non-technical stakeholders.',
    preferred_vocabulary: ['project delivery', 'BIM coordination', 'site safety', 'cost control', 'prefabrication', 'digital twin', 'lean construction', 'modular building'],
    banned_phrases: ['zero risk', 'guaranteed on-time', 'no delays'],
    voice_name: 'BuildRight Professional',
    voice_description: 'Authoritative and grounded. Uses data-driven language with practical construction insights. Balances innovation with proven reliability and an unwavering commitment to safety.',
  },

  agentTasks: {
    social_task: 'Creating thought leadership content about digital twin adoption in infrastructure for #ConstructionTech community',
    email_task: 'A/B testing nurture sequence for construction directors — personalized case studies by project type and contract value',
    ads_task: 'Optimizing Google Ads for "construction project management software" and "BIM collaboration platform" keywords',
    analytics_task: 'Analyzing conversion funnel for general contractors — 38% increase in demo requests from infrastructure segment detected',
    orchestrator_task: 'Coordinating campaign launch for World of Concrete Europe conference lead generation',
  },

  leads: [
    { name: 'Jeroen van Helden', email: 'j.vanhelden@bamgroep.nl', company: 'BAM Group', title: 'VP Operations', composite_score: 96, stage: 'sql', conversion_probability: 0.91, predicted_value: 210000, hot_signals: ['Requested enterprise platform demo', 'Downloaded BIM integration whitepaper', 'Visited pricing 5x'], cold_signals: [], source: 'World of Concrete Europe', tags: ['enterprise', 'tier-1-contractor'], next_best_action: 'Schedule executive demo with C-suite and BIM team', intent_level: 'very_high', buying_stage: 'evaluation' },
    { name: 'Marieke de Boer', email: 'm.deboer@heijmans.nl', company: 'Heijmans N.V.', title: 'Project Director', composite_score: 92, stage: 'sql', conversion_probability: 0.84, predicted_value: 175000, hot_signals: ['Attended BIM webinar series', 'Engaged with 4 case studies', 'Requested ROI analysis'], cold_signals: [], source: 'Webinar', tags: ['enterprise', 'infrastructure'], next_best_action: 'Send ROI calculator customized for infrastructure projects', intent_level: 'very_high', buying_stage: 'evaluation' },
    { name: 'Pieter Kooiman', email: 'p.kooiman@volkerwessels.com', company: 'VolkerWessels', title: 'Head of Digital Construction', composite_score: 89, stage: 'sql', conversion_probability: 0.78, predicted_value: 195000, hot_signals: ['Downloaded digital twin guide', 'Visited product pages 7x', 'CTO referral'], cold_signals: [], source: 'Partner Referral', tags: ['enterprise', 'digital-transformation'], next_best_action: 'Arrange technical deep-dive with engineering team', intent_level: 'high', buying_stage: 'evaluation' },
    { name: 'Sophie Willems', email: 's.willems@besix.com', company: 'BESIX Group', title: 'Head of Project Controls', composite_score: 85, stage: 'mql', conversion_probability: 0.69, predicted_value: 145000, hot_signals: ['Downloaded cost control guide', 'Opened 9 emails this month'], cold_signals: ['Budget cycle in Q4'], source: 'Content Download', tags: ['enterprise', 'belgium'], next_best_action: 'Invite to private roundtable on cost optimization', intent_level: 'high', buying_stage: 'consideration' },
    { name: 'Lars Henriksen', email: 'l.henriksen@ncc.dk', company: 'NCC Group Denmark', title: 'Construction Manager', composite_score: 82, stage: 'mql', conversion_probability: 0.62, predicted_value: 110000, hot_signals: ['Submitted contact form', 'Watched safety tech demo video'], cold_signals: ['Long procurement cycle'], source: 'Organic Search', tags: ['enterprise', 'nordic'], next_best_action: 'Send Nordic construction customer success stories', intent_level: 'medium', buying_stage: 'consideration' },
    { name: 'Thomas Gruber', email: 't.gruber@strabag.com', company: 'STRABAG SE', title: 'Director of Digital Engineering', composite_score: 90, stage: 'sql', conversion_probability: 0.80, predicted_value: 230000, hot_signals: ['Requested pilot program details', 'Downloaded technical architecture docs', 'Board referral'], cold_signals: [], source: 'BIM World Munich', tags: ['enterprise', 'austria', 'bim-leader'], next_best_action: 'Schedule pilot deployment discussion with IT and project leads', intent_level: 'very_high', buying_stage: 'decision' },
    { name: 'Anne-Marie Visser', email: 'a.visser@dura-vermeer.nl', company: 'Dura Vermeer', title: 'Manager Innovation & Sustainability', composite_score: 78, stage: 'mql', conversion_probability: 0.55, predicted_value: 85000, hot_signals: ['Attended sustainability webinar', 'Downloaded prefab guide'], cold_signals: ['Evaluating 3 vendors'], source: 'LinkedIn Ad', tags: ['mid-market', 'sustainability'], next_best_action: 'Send sustainability-focused case study', intent_level: 'medium', buying_stage: 'consideration' },
    { name: 'Jan Vermeulen', email: 'j.vermeulen@vanwijnen.nl', company: 'Van Wijnen', title: 'IT Infrastructure Manager', composite_score: 74, stage: 'lead', conversion_probability: 0.42, predicted_value: 70000, hot_signals: ['Visited integration documentation'], cold_signals: ['Technical evaluation only'], source: 'Google Ads', tags: ['mid-market', 'technical'], next_best_action: 'Send technical integration guide and API documentation', intent_level: 'medium', buying_stage: 'awareness' },
    { name: 'Henrik Lindqvist', email: 'h.lindqvist@skanska.se', company: 'Skanska Sweden', title: 'Chief Project Officer', composite_score: 88, stage: 'mql', conversion_probability: 0.74, predicted_value: 200000, hot_signals: ['Watched 3 customer testimonial videos', 'Requested EU pricing'], cold_signals: ['Skanska global procurement process'], source: 'Webinar', tags: ['enterprise', 'sweden', 'global-contractor'], next_best_action: 'Connect with Nordics sales team for Skanska-specific demo', intent_level: 'high', buying_stage: 'consideration' },
    { name: 'Marc Peeters', email: 'm.peeters@jandenul.com', company: 'Jan De Nul Group', title: 'Head of Project Technology', composite_score: 76, stage: 'lead', conversion_probability: 0.44, predicted_value: 120000, hot_signals: ['Downloaded marine construction case study'], cold_signals: ['Early research phase'], source: 'Content Marketing', tags: ['enterprise', 'belgium', 'marine'], next_best_action: 'Enroll in monthly construction innovation newsletter', intent_level: 'low', buying_stage: 'awareness' },
  ],

  campaigns: [
    { name: 'BIM Adoption Campaign', description: 'Multi-channel campaign educating construction leaders on BIM Level 2 adoption and ROI for project delivery', objective: 'awareness', status: 'active', budget_total: 35000, budget_spent: 22400, days_remaining: 22, roi: 310, conversions: 98, ai_managed: true, performance_score: 93 },
    { name: 'Construction Safety Tech Launch', description: 'Product launch campaign for new IoT-powered site safety monitoring module', objective: 'product_launch', status: 'active', budget_total: 50000, budget_spent: 31000, days_remaining: 28, roi: 390, conversions: 142, ai_managed: false, performance_score: 95 },
    { name: 'Infrastructure Project Management Webinar Series', description: 'Monthly webinar series on managing large-scale infrastructure projects with digital tools', objective: 'thought_leadership', status: 'active', budget_total: 14000, budget_spent: 8600, days_remaining: 55, roi: 420, conversions: 185, ai_managed: false, performance_score: 91 },
    { name: 'General Contractor Nurture Program', description: 'Long-term nurture campaign targeting general contractors with ROI case studies and project templates', objective: 'nurture', status: 'active', budget_total: 18000, budget_spent: 11200, days_remaining: 40, roi: 480, conversions: 41, ai_managed: true, performance_score: 89 },
    { name: 'World of Concrete Europe Lead Generation', description: 'Pre-event, on-site, and post-event campaign for World of Concrete Europe conference', objective: 'lead_generation', status: 'active', budget_total: 42000, budget_spent: 26800, days_remaining: 16, roi: 360, conversions: 113, ai_managed: true, performance_score: 96 },
  ],

  content: [
    { title: 'How BIM Level 2 Reduces Rework by 35%: A Data-Driven Analysis', body: 'Discover how Building Information Modeling at Level 2 maturity is eliminating costly rework on construction sites, with data from 120+ European infrastructure projects.', content_type: 'blog_post', channels: ['blog', 'linkedin', 'email'], status: 'published', tags: ['BIM', 'rework-reduction', 'thought-leadership'], performance: { impressions: 28700, clicks: 2340, shares: 389, conversions: 54 } },
    { title: 'The Complete Guide to Construction Site Safety Technology', body: 'A comprehensive guide covering IoT sensors, wearable safety devices, drone inspections, and AI-powered hazard detection for modern construction sites.', content_type: 'whitepaper', channels: ['email', 'linkedin'], status: 'published', tags: ['safety', 'IoT', 'guide'], performance: { impressions: 15600, clicks: 1890, shares: 267, conversions: 92 } },
    { title: 'Case Study: How BAM Group Achieved 28% Cost Savings with BuildRight', body: 'Learn how one of the Netherlands\' largest contractors implemented BuildRight to streamline project controls and reduce cost overruns across a portfolio of 40+ active projects.', content_type: 'case_study', channels: ['email', 'linkedin', 'blog'], status: 'published', tags: ['case-study', 'ROI', 'enterprise'] },
    { title: 'Digital Twins in Construction: From Concept to Completion', body: 'Explore how digital twin technology is transforming construction project delivery, enabling real-time monitoring and predictive maintenance from foundation to handover.', content_type: 'blog_post', channels: ['blog', 'linkedin'], status: 'published', tags: ['digital-twin', 'innovation', 'project-delivery'] },
    { title: 'Prefabrication and Modular Building: The Future of Faster Construction', body: 'How prefabrication and modular building methods are cutting project timelines by 50% while improving quality and reducing waste on European construction sites.', content_type: 'blog_post', channels: ['blog', 'linkedin', 'twitter'], status: 'published', tags: ['prefabrication', 'modular', 'sustainability'] },
    { title: 'ROI Calculator: Construction Project Management Automation', body: 'Interactive tool showing the financial impact of automating project scheduling, cost tracking, and resource allocation based on project size and complexity.', content_type: 'interactive', channels: ['email', 'linkedin'], status: 'published', tags: ['ROI', 'calculator', 'lead-magnet'] },
    { title: 'Webinar: AI-Powered Risk Prediction for Construction Projects', body: 'Join our panel of senior project directors and AI engineers as they discuss how machine learning predicts project delays and cost overruns before they happen.', content_type: 'webinar', channels: ['email', 'linkedin', 'facebook'], status: 'published', tags: ['webinar', 'AI', 'risk-management'] },
    { title: 'Infographic: The State of Construction Technology in Europe 2026', body: 'Visual overview of construction tech adoption rates, digital investment trends, and technology priorities across European construction firms.', content_type: 'infographic', channels: ['linkedin', 'twitter', 'instagram'], status: 'published', tags: ['infographic', 'market-data', 'europe'] },
    { title: 'Sustainability in Construction: Reducing Carbon with Digital Tools', body: 'Step-by-step guide for construction leaders on tracking and reducing embodied carbon through digital material management and lifecycle analysis tools.', content_type: 'guide', channels: ['email', 'blog'], status: 'scheduled', tags: ['sustainability', 'carbon', 'leadership'] },
    { title: 'Video: Customer Success Story — Heijmans N.V.', body: 'Watch how Heijmans improved project schedule adherence by 42% and reduced safety incidents by 60% with BuildRight\'s integrated platform.', content_type: 'video', channels: ['youtube', 'linkedin', 'email'], status: 'scheduled', tags: ['video', 'customer-story', 'testimonial'] },
    { title: 'Lean Construction: Eliminating Waste in Modern Project Delivery', body: 'How BuildRight integrates lean construction principles into digital project management, from Last Planner System to pull planning and constraint analysis.', content_type: 'blog_post', channels: ['blog', 'linkedin'], status: 'draft', tags: ['lean-construction', 'methodology', 'efficiency'] },
    { title: 'Social Post: World of Concrete Europe Preview', body: 'We\'re excited to announce our presence at World of Concrete Europe 2026! Visit stand #312 for live demos of our new Safety Monitor module.', content_type: 'social_post', channels: ['linkedin', 'twitter', 'facebook'], status: 'scheduled', tags: ['event', 'conference', 'announcement'] },
    { title: 'Email: Monthly Construction Innovation Digest', body: 'Curated monthly newsletter featuring the latest in construction technology, project management best practices, and BuildRight product updates.', content_type: 'newsletter', channels: ['email'], status: 'published', tags: ['newsletter', 'monthly', 'innovation'] },
    { title: 'Podcast: Construction Leaders — Episode 8', body: 'Interview with Jeroen van Helden on scaling digital project management across a portfolio of 200+ projects and lessons from large-scale BIM adoption.', content_type: 'podcast', channels: ['spotify', 'linkedin', 'email'], status: 'draft', tags: ['podcast', 'interview', 'thought-leadership'] },
    { title: 'LinkedIn Carousel: 7 KPIs Every Construction Director Should Track', body: 'Visual guide to the most important project performance KPIs, from schedule variance and cost performance index to safety incident rates and RFI turnaround time.', content_type: 'carousel', channels: ['linkedin'], status: 'published', tags: ['carousel', 'KPIs', 'construction-director'] },
  ],

  competitors: [
    { name: 'SiteForce Pro', description: 'Established construction project management vendor with strong market presence in Western Europe', website: 'siteforcepro.com', market_share: 24, strengths: ['Large install base', 'Comprehensive project controls', 'Strong contractor partnerships'], weaknesses: ['Slow to adopt BIM', 'Complex implementation', 'Outdated user interface'] },
    { name: 'ProBuild Digital', description: 'Fast-growing startup focused on AI-powered construction scheduling and resource optimization', website: 'probuild-digital.com', market_share: 10, strengths: ['Strong AI capabilities', 'Modern interface', 'Quick deployment'], weaknesses: ['Limited enterprise features', 'Small customer base', 'No on-premise option'] },
    { name: 'ConstructIQ', description: 'Mid-market player specializing in construction cost estimation and budget management', website: 'constructiq.eu', market_share: 16, strengths: ['Best-in-class cost estimation', 'Quantity surveying tools', 'Strong EU presence'], weaknesses: ['No BIM integration', 'Limited field tools', 'Basic reporting'] },
    { name: 'BIMConnect', description: 'BIM collaboration platform with strong integrations to Autodesk and Trimble ecosystems', website: 'bimconnect.io', market_share: 11, strengths: ['Excellent BIM viewer', 'Deep Autodesk integration', 'Model coordination'], weaknesses: ['BIM-only focus', 'No project management', 'Limited safety features'] },
  ],

  events: [
    { name: 'World of Concrete Europe 2026', type: 'conference', description: 'Largest construction technology and materials conference in Europe with 9,000+ attendees', location: 'RAI Amsterdam', city: 'Amsterdam', country: 'Netherlands', date_start: daysFromNow(16), date_end: daysFromNow(19), expected_attendees: 9200, target_audience_match: 94, estimated_roi: 480, estimated_leads: 95, networking_value: 96, cost: 28000, topics: ['Construction Technology', 'BIM', 'Safety Innovation', 'Sustainable Building'], status: 'confirmed', priority_score: 97 },
    { name: 'BIM World Munich 2026', type: 'summit', description: 'Premier summit for BIM and digital construction leaders in the DACH region', location: 'ICM Munich', city: 'Munich', country: 'Germany', date_start: daysFromNow(42), date_end: daysFromNow(43), expected_attendees: 3500, target_audience_match: 90, estimated_roi: 350, estimated_leads: 45, networking_value: 92, cost: 12000, topics: ['BIM Standards', 'Digital Twins', 'ISO 19650', 'Smart Construction'], status: 'confirmed', priority_score: 88 },
    { name: 'Bouwend Nederland Congress', type: 'technical', description: 'Annual congress of the Dutch construction industry association covering innovation and policy', location: 'Jaarbeurs Utrecht', city: 'Utrecht', country: 'Netherlands', date_start: daysFromNow(65), date_end: daysFromNow(66), expected_attendees: 1800, target_audience_match: 82, estimated_roi: 220, estimated_leads: 30, networking_value: 85, cost: 7500, topics: ['Construction Innovation', 'Workforce Development', 'Sustainability Regulation', 'Prefabrication'], status: 'evaluating', priority_score: 76 },
  ],

  personas: [
    { name: 'Dirk — The Construction Director', description: 'Senior executive overseeing multiple large-scale construction projects and P&L responsibility', demographics: { age: '48-58', education: 'Civil Engineering + MBA', income: '\u20AC160K-\u20AC220K', location: 'Major contractor headquarters' }, psychographics: { motivation: 'Deliver projects on time and under budget', decision_style: 'Data-driven, risk-aware, consensus-builder', risk_tolerance: 'Moderate \u2014 needs proven ROI and reference projects' }, pain_points: ['Project cost overruns', 'Schedule delays and coordination issues', 'Fragmented tooling across project teams', 'Compliance and safety reporting burden'], goals: ['Reduce cost overruns by 30%', 'Achieve 95% schedule adherence', 'Standardize project management across all sites'], preferred_channels: ['LinkedIn', 'Email', 'Industry conferences', 'Peer recommendations'] },
    { name: 'Eva — The Site Project Manager', description: 'Hands-on project manager responsible for day-to-day site coordination and subcontractor management', demographics: { age: '32-42', education: 'Construction Management or Civil Engineering', income: '\u20AC70K-\u20AC95K', location: 'On-site / regional office' }, psychographics: { motivation: 'Keep the project running smoothly and safely', decision_style: 'Practical, mobile-first, user-experience focused', risk_tolerance: 'Low \u2014 needs reliable tools that work on-site' }, pain_points: ['Paper-based daily reports', 'Poor communication with subcontractors', 'Tracking RFIs and change orders', 'Real-time progress visibility'], goals: ['Eliminate paper-based reporting', 'Reduce RFI turnaround to under 48 hours', 'Real-time project dashboards from the field'], preferred_channels: ['Email', 'Webinars', 'Mobile apps', 'Trade publications'] },
    { name: 'Floris — The BIM & Innovation Lead', description: 'Technology-focused professional driving digital transformation and BIM adoption in a construction firm', demographics: { age: '30-40', education: 'Architecture / Computational Design / BIM Management', income: '\u20AC85K-\u20AC120K', location: 'Head office / innovation lab' }, psychographics: { motivation: 'Lead digital construction transformation', decision_style: 'Early adopter, technology-first, integration-focused', risk_tolerance: 'High \u2014 willing to pilot new solutions and push boundaries' }, pain_points: ['Resistance to BIM adoption from field teams', 'Data silos between design and construction', 'Proving ROI for digital investments', 'Interoperability between BIM authoring tools'], goals: ['Achieve ISO 19650 compliance across all projects', 'Build a connected digital twin ecosystem', 'Integrate BIM with project management and cost systems'], preferred_channels: ['LinkedIn', 'Tech conferences', 'BIM community forums', 'Developer documentation'] },
  ],

  products: [
    { name: 'BuildRight Project Hub', description: 'AI-powered construction project management platform with scheduling, cost tracking, resource allocation, and real-time project dashboards', category: 'Platform', status: 'active', price_range: '\u20AC40K-\u20AC180K/year', target_audience: 'General contractors with 10+ active projects', key_features: ['AI schedule optimization', 'Cost performance tracking', 'Resource allocation engine', 'Real-time project dashboards', 'Subcontractor portal'], competitive_advantages: ['30% reduction in cost overruns', 'BIM-native architecture', '99.9% uptime SLA'] },
    { name: 'BuildRight BIM Connect', description: 'BIM collaboration and coordination module with model viewing, clash detection, and design-to-construction data flow', category: 'Module', status: 'active', price_range: '\u20AC15K-\u20AC65K/year', target_audience: 'Construction firms adopting BIM Level 2+', key_features: ['3D model viewer', 'Automated clash detection', 'IFC import/export', 'Design review workflows', 'BIM-to-field data sync'], competitive_advantages: ['Supports all major BIM formats', 'Real-time model coordination', 'ISO 19650 compliant workflows'] },
    { name: 'BuildRight Safety Monitor', description: 'IoT-integrated site safety monitoring with wearable tracking, hazard alerts, incident reporting, and compliance dashboards', category: 'Add-on', status: 'active', price_range: '\u20AC10K-\u20AC45K/year', target_audience: 'Safety-conscious contractors and site operators', key_features: ['IoT sensor integration', 'Wearable worker tracking', 'Hazard alert system', 'Incident reporting', 'Compliance dashboard'], competitive_advantages: ['60% reduction in safety incidents', 'Real-time zone monitoring', 'Automated regulatory reporting'] },
  ],

  strategicObjectives: [
    { name: 'Market Leadership in EU Construction Tech', description: 'Become the #1 construction project management platform in Europe by 2027', category: 'growth', target_value: 22, current_value: 15, unit: 'market_share_%', priority: 'high' },
    { name: 'ARR Growth Target', description: 'Achieve \u20AC15M ARR by end of 2026', category: 'revenue', target_value: 15000000, current_value: 10200000, unit: 'EUR', priority: 'critical' },
    { name: 'Safety Module Adoption', description: 'Onboard 150 construction sites onto BuildRight Safety Monitor', category: 'product', target_value: 150, current_value: 87, unit: 'sites', priority: 'high' },
    { name: 'Customer Retention Excellence', description: 'Maintain net revenue retention above 115% across all products', category: 'customer_success', target_value: 115, current_value: 118, unit: 'NRR_%', priority: 'medium' },
  ],

  organizationEntities: [
    { name: 'Product & Engineering', type: 'department', description: 'Core platform development, BIM tools, AI/ML research, and infrastructure engineering' },
    { name: 'Sales & Partnerships', type: 'department', description: 'Enterprise sales, channel partnerships with contractors, and new market expansion' },
    { name: 'Marketing & Communications', type: 'department', description: 'Brand, content, demand generation, events, and construction industry PR' },
    { name: 'Customer Success & Implementation', type: 'department', description: 'Onboarding, training, technical support, and account management for construction clients' },
    { name: 'Construction Advisory Board', type: 'advisory', description: 'External panel of senior construction professionals guiding product development and industry alignment' },
  ],

  // Finance data
  financeCustomers: [
    { name: 'BAM Group', email: 'finance@bamgroep.nl', phone: '+31 30 659 8911', address: 'Runnenburg 9', city: 'Bunnik', postal_code: '3981 AZ', country: 'Netherlands', contact_person: 'Jeroen van Helden', kvk_number: '30058019', btw_number: 'NL001852087B01', payment_terms: 30, status: 'active' },
    { name: 'Heijmans N.V.', email: 'crediteuren@heijmans.nl', phone: '+31 73 543 5111', address: 'Graafsebaan 67', city: 'Rosmalen', postal_code: '5248 JT', country: 'Netherlands', contact_person: 'Marieke de Boer', kvk_number: '16068452', btw_number: 'NL004561903B01', payment_terms: 30, status: 'active' },
    { name: 'STRABAG SE', email: 'rechnungswesen@strabag.com', phone: '+43 1 22422 0', address: 'Donau-City-Strasse 9', city: 'Vienna', postal_code: '1220', country: 'Austria', contact_person: 'Thomas Gruber', kvk_number: '', btw_number: 'ATU63760811', payment_terms: 45, status: 'active' },
    { name: 'BESIX Group', email: 'comptabilite@besix.com', phone: '+32 2 402 6211', address: 'Avenue des Communautes 100', city: 'Brussels', postal_code: '1200', country: 'Belgium', contact_person: 'Sophie Willems', kvk_number: '', btw_number: 'BE0400.063.727', payment_terms: 30, status: 'active' },
    { name: 'VolkerWessels', email: 'finance@volkerwessels.com', phone: '+31 33 277 2500', address: 'Podium 9', city: 'Amersfoort', postal_code: '3826 PA', country: 'Netherlands', contact_person: 'Pieter Kooiman', kvk_number: '31038604', btw_number: 'NL008548819B01', payment_terms: 30, status: 'active' },
    { name: 'Skanska Sweden', email: 'ekonomi@skanska.se', phone: '+46 10 448 0000', address: 'Warfvinges vag 25', city: 'Stockholm', postal_code: '112 74', country: 'Sweden', contact_person: 'Henrik Lindqvist', kvk_number: '', btw_number: 'SE556302635701', payment_terms: 30, status: 'active' },
    { name: 'NCC Group Denmark', email: 'okonomi@ncc.dk', phone: '+45 39 10 39 10', address: 'Tuborgvej 15', city: 'Hellerup', postal_code: '2900', country: 'Denmark', contact_person: 'Lars Henriksen', kvk_number: '', btw_number: 'DK26444437', payment_terms: 30, status: 'active' },
    { name: 'Dura Vermeer', email: 'debiteuren@duravermeer.nl', phone: '+31 30 263 9111', address: 'Piet Mondriaanlaan 36', city: 'Houten', postal_code: '3991 BE', country: 'Netherlands', contact_person: 'Anne-Marie Visser', kvk_number: '27172653', btw_number: 'NL005765432B01', payment_terms: 30, status: 'active' },
  ],

  financeSuppliers: [
    { name: 'AWS Cloud Services', email: 'billing@amazon.com', phone: '+1 206 266 1000', address: '410 Terry Avenue North', city: 'Seattle', postal_code: '98109', country: 'USA', contact_person: 'Cloud Services Team', kvk_number: '', btw_number: 'US911646860', payment_terms: 30, status: 'active' },
    { name: 'Autodesk BIM Solutions', email: 'accounts@autodesk.com', phone: '+1 415 507 5000', address: 'One Market Street', city: 'San Francisco', postal_code: '94105', country: 'USA', contact_person: 'Enterprise Licensing', kvk_number: '', btw_number: 'US943320693', payment_terms: 30, status: 'active' },
    { name: 'ConstructionMark Agency', email: 'accounts@constructionmark.nl', phone: '+31 20 555 0300', address: 'Keizersgracht 220', city: 'Amsterdam', postal_code: '1016 DZ', country: 'Netherlands', contact_person: 'Roel Janssen', kvk_number: '71234567', btw_number: 'NL859012345B01', payment_terms: 14, status: 'active' },
    { name: 'IoT Sensor Systems GmbH', email: 'rechnungen@iot-sensors.de', phone: '+49 89 555 4321', address: 'Leopoldstrasse 150', city: 'Munich', postal_code: '80804', country: 'Germany', contact_person: 'Hardware Division', kvk_number: '', btw_number: 'DE312345678', payment_terms: 30, status: 'active' },
    { name: 'TechTalent Partners', email: 'invoicing@techtalent.nl', phone: '+31 30 555 0400', address: 'Croeselaan 18', city: 'Utrecht', postal_code: '3521 CB', country: 'Netherlands', contact_person: 'HR Services', kvk_number: '82345678', btw_number: 'NL862345678B01', payment_terms: 14, status: 'active' },
  ],

  financeInvoices: [
    { invoice_type: 'sales', entity_name: 'BAM Group', description: 'BuildRight Project Hub \u2014 Annual Enterprise License Q1 2026', subtotal: 52000, tax_amount: 10920, total_amount: 62920, status: 'paid', days_offset: -60 },
    { invoice_type: 'sales', entity_name: 'Heijmans N.V.', description: 'BuildRight Project Hub + BIM Connect \u2014 Implementation & License', subtotal: 44000, tax_amount: 9240, total_amount: 53240, status: 'paid', days_offset: -45 },
    { invoice_type: 'sales', entity_name: 'STRABAG SE', description: 'BuildRight Project Hub \u2014 Enterprise Multi-Site License', subtotal: 78000, tax_amount: 14820, total_amount: 92820, status: 'pending', days_offset: -15 },
    { invoice_type: 'sales', entity_name: 'Skanska Sweden', description: 'BuildRight BIM Connect \u2014 Annual Subscription', subtotal: 48000, tax_amount: 10080, total_amount: 58080, status: 'pending', days_offset: -10 },
    { invoice_type: 'sales', entity_name: 'Dura Vermeer', description: 'BuildRight Safety Monitor \u2014 License + IoT Setup', subtotal: 32000, tax_amount: 6720, total_amount: 38720, status: 'paid', days_offset: -90 },
    { invoice_type: 'sales', entity_name: 'BESIX Group', description: 'BuildRight Project Hub \u2014 Pilot Program (6 months)', subtotal: 21000, tax_amount: 4410, total_amount: 25410, status: 'overdue', days_offset: -75 },
    { invoice_type: 'sales', entity_name: 'NCC Group Denmark', description: 'Consulting \u2014 BIM Implementation Assessment', subtotal: 14500, tax_amount: 3045, total_amount: 17545, status: 'paid', days_offset: -30 },
    { invoice_type: 'sales', entity_name: 'VolkerWessels', description: 'BuildRight Safety Monitor \u2014 Quarterly License', subtotal: 11000, tax_amount: 2310, total_amount: 13310, status: 'pending', days_offset: -5 },
    { invoice_type: 'purchase', entity_name: 'AWS Cloud Services', description: 'Cloud Hosting \u2014 Construction Platform Infrastructure Q1', subtotal: 21000, tax_amount: 4410, total_amount: 25410, status: 'paid', days_offset: -30 },
    { invoice_type: 'purchase', entity_name: 'Autodesk BIM Solutions', description: 'Forge API \u2014 Enterprise License + BIM 360 Integration', subtotal: 16500, tax_amount: 3135, total_amount: 19635, status: 'paid', days_offset: -45 },
    { invoice_type: 'purchase', entity_name: 'ConstructionMark Agency', description: 'World of Concrete Europe 2026 Campaign Design & Materials', subtotal: 14000, tax_amount: 2940, total_amount: 16940, status: 'pending', days_offset: -14 },
    { invoice_type: 'purchase', entity_name: 'TechTalent Partners', description: 'BIM Domain Expert \u2014 3 month contract', subtotal: 25500, tax_amount: 5355, total_amount: 30855, status: 'paid', days_offset: -60 },
    { invoice_type: 'purchase', entity_name: 'IoT Sensor Systems GmbH', description: 'Safety Sensor Hardware \u2014 Batch Order 200 units', subtotal: 38000, tax_amount: 7220, total_amount: 45220, status: 'paid', days_offset: -20 },
    { invoice_type: 'sales', entity_name: 'BAM Group', description: 'BuildRight Safety Monitor \u2014 Add-on Module (15 sites)', subtotal: 28000, tax_amount: 5880, total_amount: 33880, status: 'draft', days_offset: 0 },
    { invoice_type: 'purchase', entity_name: 'AWS Cloud Services', description: 'Cloud Hosting \u2014 Construction Platform Infrastructure Q2', subtotal: 22500, tax_amount: 4725, total_amount: 27225, status: 'draft', days_offset: 0 },
  ],

  financeBudgets: [
    { category: 'Cloud Infrastructure & Hosting', budgeted_amount: 95000, actual_amount: 72000 },
    { category: 'Marketing & Events', budgeted_amount: 140000, actual_amount: 98000 },
    { category: 'Research & Development', budgeted_amount: 420000, actual_amount: 335000 },
    { category: 'Personnel', budgeted_amount: 1100000, actual_amount: 840000 },
    { category: 'IoT Hardware & Sensors', budgeted_amount: 180000, actual_amount: 125000 },
    { category: 'Sales & Business Development', budgeted_amount: 95000, actual_amount: 64000 },
  ],

  financeGoals: [
    { goal: 'Achieve \u20AC15M ARR', category: 'revenue', target_value: 15000000, current_value: 10200000, unit: 'EUR', status: 'on_track' },
    { goal: 'Maintain gross margin above 72%', category: 'profitability', target_value: 72, current_value: 75, unit: '%', status: 'achieved' },
    { goal: 'Reduce customer acquisition cost by 18%', category: 'efficiency', target_value: 18, current_value: 12, unit: '%', status: 'on_track' },
    { goal: 'Secure Series B funding', category: 'funding', target_value: 20000000, current_value: 0, unit: 'EUR', status: 'in_progress' },
  ],

  yearPlanName: 'BuildRight Group \u2014 Financial Plan 2026',
};
