// src/services/demo-agent/templates/it.template.ts
import type { IndustryTemplate } from '../types';
import { daysFromNow } from './base-template';

export const itTemplate: IndustryTemplate = {
  industry: 'it',

  brand: {
    name: 'CloudNexus Technologies',
    tagline: 'Intelligent Cloud, Infinite Possibilities',
    mission: 'To empower engineering teams with an intelligent cloud platform that automates infrastructure, accelerates delivery, and eliminates operational complexity.',
    description: 'CloudNexus Technologies is a B2B SaaS company providing an integrated cloud infrastructure, DevOps automation, and Kubernetes management platform for fast-growing technology companies across Europe. Our unified control plane combines CI/CD pipelines, container orchestration, infrastructure as code, and real-time observability.',
    tone_attributes: ['Technical yet accessible', 'Innovative', 'Developer-friendly', 'Confident'],
    primary_color: '#8B5CF6',
    secondary_color: '#6D28D9',
    usps: ['60% faster deployments with AI-powered pipelines', 'Unified Kubernetes management across multi-cloud', 'Infrastructure as Code with drift detection', 'Zero-downtime migrations guaranteed'],
    brand_values: ['Developer experience', 'Reliability', 'Open standards', 'Continuous innovation', 'Security by default'],
    audiences: ['CTOs', 'VP Engineering', 'DevOps team leads', 'Cloud architects', 'Platform engineering managers'],
    industries: ['SaaS', 'FinTech', 'E-commerce', 'Cloud-native startups', 'Enterprise IT'],
    messaging_dos: 'Use concrete metrics and benchmarks. Reference open-source standards. Speak to engineering pain points with technical credibility. Show respect for developer time.',
    messaging_donts: 'Never overpromise on uptime without SLA backing. Avoid buzzwords without substance. Do not diminish open-source alternatives.',
    preferred_vocabulary: ['platform engineering', 'deployment velocity', 'infrastructure as code', 'observability', 'GitOps', 'shift-left', 'developer experience', 'cloud-native'],
    banned_phrases: ['silver bullet', 'just works magically', 'no DevOps needed'],
    voice_name: 'CloudNexus Engineering Voice',
    voice_description: 'Technically precise but never condescending. Speaks like a senior engineer explaining to a peer. Balances innovation excitement with operational pragmatism.',
  },

  agentTasks: {
    social_task: 'Creating developer-focused thought leadership thread on platform engineering trends for #DevOps and #Kubernetes communities',
    email_task: 'A/B testing nurture sequence for VP Engineering personas — personalizing by cloud provider and team size',
    ads_task: 'Optimizing Google Ads for "Kubernetes management platform" and "CI/CD automation" high-intent keywords',
    analytics_task: 'Analyzing pipeline-to-close conversion for DevOps leads — 38% uplift in demo-to-trial conversion detected',
    orchestrator_task: 'Coordinating multi-channel launch campaign for KubeCon Europe 2026 booth and speaking slot',
  },

  leads: [
    { name: 'Sander van Dijk', email: 's.vandijk@techventure.nl', company: 'TechVenture Amsterdam', title: 'CTO', composite_score: 96, stage: 'sql', conversion_probability: 0.91, predicted_value: 145000, hot_signals: ['Requested enterprise demo', 'Downloaded Kubernetes migration guide', 'Visited pricing 6x this week'], cold_signals: [], source: 'KubeCon Europe', tags: ['enterprise', 'kubernetes', 'high-priority'], next_best_action: 'Schedule technical deep-dive with solutions architect', intent_level: 'very_high', buying_stage: 'evaluation' },
    { name: 'Lena Hoffmann', email: 'l.hoffmann@scaleup-berlin.de', company: 'ScaleUp Berlin', title: 'VP Engineering', composite_score: 92, stage: 'sql', conversion_probability: 0.84, predicted_value: 120000, hot_signals: ['Attended CI/CD webinar', 'Engaged with 4 case studies', 'Team evaluated free tier'], cold_signals: [], source: 'Webinar', tags: ['scale-up', 'ci-cd', 'germany'], next_best_action: 'Send multi-team pricing proposal with volume discount', intent_level: 'very_high', buying_stage: 'evaluation' },
    { name: 'Antoine Leroy', email: 'a.leroy@fintechbrussels.be', company: 'FinTech Brussels', title: 'Head of Cloud Infrastructure', composite_score: 88, stage: 'mql', conversion_probability: 0.72, predicted_value: 95000, hot_signals: ['Downloaded cloud cost optimization whitepaper', 'Opened 9 emails in 2 weeks'], cold_signals: ['Compliance review in progress'], source: 'Content Download', tags: ['fintech', 'compliance', 'belgium'], next_best_action: 'Invite to FinTech security compliance roundtable', intent_level: 'high', buying_stage: 'consideration' },
    { name: 'Maja Lindqvist', email: 'm.lindqvist@nordiccloud.se', company: 'Nordic Cloud Solutions', title: 'DevOps Lead', composite_score: 85, stage: 'mql', conversion_probability: 0.66, predicted_value: 78000, hot_signals: ['Visited product pages 8x', 'Submitted contact form', 'Active GitHub contributor'], cold_signals: ['Team size under 20'], source: 'Organic Search', tags: ['devops', 'nordic', 'mid-market'], next_best_action: 'Send Nordic customer success stories and team pricing', intent_level: 'high', buying_stage: 'consideration' },
    { name: 'Pieter de Groot', email: 'p.degroot@cloudnine.nl', company: 'CloudNine Payments', title: 'Cloud Architect', composite_score: 82, stage: 'mql', conversion_probability: 0.61, predicted_value: 110000, hot_signals: ['Attended 2 webinars', 'Downloaded IaC comparison guide'], cold_signals: ['Evaluating 3 vendors simultaneously'], source: 'LinkedIn Ad', tags: ['payments', 'architecture', 'netherlands'], next_best_action: 'Send competitive differentiation deck vs. legacy IaC tools', intent_level: 'medium', buying_stage: 'evaluation' },
    { name: 'Dr. Katarina Novak', email: 'k.novak@datastream.at', company: 'DataStream Vienna', title: 'CTO', composite_score: 90, stage: 'sql', conversion_probability: 0.80, predicted_value: 135000, hot_signals: ['Requested pilot program details', 'CTO referral from existing customer', 'Downloaded enterprise architecture docs'], cold_signals: [], source: 'Partner Referral', tags: ['enterprise', 'data-platform', 'austria'], next_best_action: 'Arrange technical proof-of-concept workshop', intent_level: 'very_high', buying_stage: 'decision' },
    { name: 'Marco Bianchi', email: 'm.bianchi@devhub.it', company: 'DevHub Milano', title: 'Head of Platform Engineering', composite_score: 77, stage: 'lead', conversion_probability: 0.44, predicted_value: 68000, hot_signals: ['Downloaded platform engineering maturity model'], cold_signals: ['Early research phase', 'Budget not yet allocated'], source: 'Content Marketing', tags: ['platform-eng', 'italy', 'mid-market'], next_best_action: 'Enroll in monthly DevOps Digest newsletter', intent_level: 'low', buying_stage: 'awareness' },
    { name: 'Emma O\'Brien', email: 'e.obrien@rapidscale.ie', company: 'RapidScale Dublin', title: 'VP Engineering', composite_score: 86, stage: 'mql', conversion_probability: 0.69, predicted_value: 92000, hot_signals: ['Watched 3 customer testimonial videos', 'Requested EU pricing sheet'], cold_signals: ['Long procurement cycle at parent company'], source: 'Webinar', tags: ['scale-up', 'ireland', 'high-growth'], next_best_action: 'Connect with EMEA sales lead for enterprise demo', intent_level: 'high', buying_stage: 'consideration' },
    { name: 'Tomasz Kowalski', email: 't.kowalski@cyberforge.pl', company: 'CyberForge Warsaw', title: 'Director of Engineering', composite_score: 74, stage: 'lead', conversion_probability: 0.41, predicted_value: 55000, hot_signals: ['Visited CI/CD documentation pages'], cold_signals: ['Technical evaluation only', 'No executive sponsor yet'], source: 'Google Ads', tags: ['engineering', 'poland', 'evaluation'], next_best_action: 'Send technical integration guide and API docs', intent_level: 'medium', buying_stage: 'awareness' },
    { name: 'Sophie Martens', email: 's.martens@logistiq.nl', company: 'LogistiQ Tech Rotterdam', title: 'Engineering Manager', composite_score: 70, stage: 'lead', conversion_probability: 0.38, predicted_value: 48000, hot_signals: ['Downloaded Kubernetes best practices ebook'], cold_signals: ['Small engineering team', 'Currently using open-source only'], source: 'LinkedIn', tags: ['logistics', 'netherlands', 'kubernetes'], next_best_action: 'Send open-source to enterprise migration path guide', intent_level: 'low', buying_stage: 'awareness' },
  ],

  campaigns: [
    { name: 'Cloud Migration Accelerator', description: 'Multi-channel campaign targeting companies migrating from on-prem or legacy cloud to modern multi-cloud architectures', objective: 'lead_generation', status: 'active', budget_total: 52000, budget_spent: 31200, days_remaining: 22, roi: 380, conversions: 142, ai_managed: true, performance_score: 95 },
    { name: 'DevOps Maturity Assessment', description: 'Interactive assessment tool campaign driving leads through a self-service DevOps maturity evaluation', objective: 'lead_generation', status: 'active', budget_total: 28000, budget_spent: 17500, days_remaining: 35, roi: 460, conversions: 98, ai_managed: true, performance_score: 93 },
    { name: 'KubeCon Europe 2026 Launch', description: 'Pre-event, on-site booth, and post-event follow-up campaign for KubeCon Europe', objective: 'event_promotion', status: 'active', budget_total: 65000, budget_spent: 38000, days_remaining: 16, roi: 310, conversions: 187, ai_managed: false, performance_score: 97 },
    { name: 'Platform Engineering Thought Leadership', description: 'Long-form content and webinar series positioning CloudNexus as the platform engineering authority', objective: 'thought_leadership', status: 'active', budget_total: 18000, budget_spent: 11400, days_remaining: 50, roi: 540, conversions: 41, ai_managed: true, performance_score: 89 },
    { name: 'CI/CD Pipeline Optimization Nurture', description: 'Email nurture sequence targeting DevOps leads with CI/CD performance benchmarks and optimization tips', objective: 'nurture', status: 'active', budget_total: 14000, budget_spent: 8200, days_remaining: 40, roi: 490, conversions: 56, ai_managed: true, performance_score: 91 },
  ],

  content: [
    { title: '10 Kubernetes Best Practices Every Platform Team Should Adopt in 2026', body: 'A comprehensive guide covering namespace strategies, resource quotas, network policies, and GitOps workflows that leading platform teams use to run production Kubernetes at scale.', content_type: 'blog_post', channels: ['blog', 'linkedin', 'twitter'], status: 'published', tags: ['kubernetes', 'best-practices', 'platform-engineering'], performance: { impressions: 42800, clicks: 3560, shares: 612, conversions: 84 } },
    { title: 'The Ultimate CI/CD Pipeline Optimization Guide', body: 'Learn how to cut build times by 60%, implement progressive delivery, and achieve zero-downtime deployments with modern CI/CD practices and CloudNexus Pipelines.', content_type: 'whitepaper', channels: ['email', 'linkedin'], status: 'published', tags: ['ci-cd', 'optimization', 'guide'], performance: { impressions: 18600, clicks: 2340, shares: 378, conversions: 112 } },
    { title: 'Case Study: How ScaleUp Berlin Reduced Deployment Time from 45 Minutes to 3 Minutes', body: 'Discover how a fast-growing Berlin fintech transformed their deployment pipeline with CloudNexus, achieving 15x faster releases and 99.99% deployment success rate.', content_type: 'case_study', channels: ['email', 'linkedin', 'blog'], status: 'published', tags: ['case-study', 'deployment', 'fintech'] },
    { title: 'Cloud Cost Optimization: A CTO\'s Playbook for Cutting Infrastructure Spend by 40%', body: 'Actionable strategies for right-sizing workloads, leveraging spot instances, implementing auto-scaling policies, and using FinOps practices to eliminate cloud waste.', content_type: 'blog_post', channels: ['blog', 'linkedin'], status: 'published', tags: ['cost-optimization', 'finops', 'cto'] },
    { title: 'Infrastructure as Code in 2026: Terraform, Pulumi, and Beyond', body: 'A deep comparison of IaC tools with real-world benchmarks, drift detection strategies, and how CloudNexus unifies multi-tool environments under a single control plane.', content_type: 'blog_post', channels: ['blog', 'linkedin', 'twitter'], status: 'published', tags: ['iac', 'terraform', 'pulumi', 'comparison'] },
    { title: 'The Platform Engineering Maturity Model', body: 'Interactive self-assessment tool that evaluates your organization across 5 dimensions: developer experience, automation, observability, security, and governance.', content_type: 'interactive', channels: ['email', 'linkedin'], status: 'published', tags: ['platform-engineering', 'maturity-model', 'lead-magnet'] },
    { title: 'Webinar: GitOps at Scale — Lessons from Running 500+ Microservices', body: 'Join our panel of senior platform engineers as they discuss GitOps patterns, Argo CD best practices, and real-world war stories from large-scale microservice architectures.', content_type: 'webinar', channels: ['email', 'linkedin', 'youtube'], status: 'published', tags: ['webinar', 'gitops', 'microservices'] },
    { title: 'Infographic: The State of DevOps in Europe 2026', body: 'Visual overview of DevOps adoption rates, tool preferences, team structures, and deployment frequency across European technology companies.', content_type: 'infographic', channels: ['linkedin', 'twitter', 'instagram'], status: 'published', tags: ['infographic', 'devops', 'market-data'] },
    { title: 'How to Build a Business Case for a Developer Platform', body: 'Step-by-step guide for engineering leaders on calculating ROI, aligning stakeholders, and presenting a compelling case for investing in internal developer platforms.', content_type: 'guide', channels: ['email', 'blog'], status: 'scheduled', tags: ['business-case', 'developer-platform', 'leadership'] },
    { title: 'Video: Customer Success Story — TechVenture Amsterdam', body: 'Watch how TechVenture Amsterdam consolidated 5 DevOps tools into one platform with CloudNexus, saving 30 engineering hours per week and reducing incident response time by 70%.', content_type: 'video', channels: ['youtube', 'linkedin', 'email'], status: 'scheduled', tags: ['video', 'customer-story', 'testimonial'] },
    { title: 'Zero-Trust Security for Kubernetes: A Practical Implementation Guide', body: 'How CloudNexus implements zero-trust networking, pod security standards, and supply chain security for enterprise Kubernetes clusters.', content_type: 'blog_post', channels: ['blog', 'linkedin'], status: 'draft', tags: ['security', 'zero-trust', 'kubernetes'] },
    { title: 'Social Post: KubeCon Europe Preview', body: 'We are thrilled to announce our Diamond sponsorship at KubeCon Europe 2026! Visit booth #C14 for live demos of CloudNexus Autopilot and our new AI-powered incident response engine.', content_type: 'social_post', channels: ['linkedin', 'twitter', 'mastodon'], status: 'scheduled', tags: ['event', 'kubecon', 'announcement'] },
    { title: 'Email: Monthly DevOps Radar Digest', body: 'Curated monthly newsletter featuring the latest in cloud-native technologies, open-source tool reviews, deployment metrics benchmarks, and CloudNexus product updates.', content_type: 'newsletter', channels: ['email'], status: 'published', tags: ['newsletter', 'monthly', 'devops'] },
    { title: 'Podcast: Cloud Native Builders — Episode 18', body: 'Interview with Sander van Dijk on scaling Kubernetes across 3 cloud providers, the cultural shift to platform engineering, and lessons from migrating a monolith to microservices.', content_type: 'podcast', channels: ['spotify', 'linkedin', 'email'], status: 'draft', tags: ['podcast', 'interview', 'thought-leadership'] },
    { title: 'LinkedIn Carousel: 7 Metrics Every DevOps Team Should Track', body: 'Visual guide to the DORA metrics and beyond — deployment frequency, lead time, change failure rate, MTTR, plus cost per deployment, developer satisfaction, and platform adoption rate.', content_type: 'carousel', channels: ['linkedin'], status: 'published', tags: ['carousel', 'metrics', 'dora'] },
  ],

  competitors: [
    { name: 'InfraHero', description: 'Well-funded infrastructure automation startup with strong enterprise sales team and AWS partnership', website: 'infrahero.io', market_share: 22, strengths: ['Deep AWS integration', 'Large enterprise customer base', 'Strong professional services'], weaknesses: ['AWS lock-in', 'Slow to support new cloud providers', 'Expensive implementation'] },
    { name: 'DeployStack', description: 'Developer-first CI/CD platform popular with startups and mid-market SaaS companies', website: 'deploystack.dev', market_share: 15, strengths: ['Excellent developer UX', 'Fast onboarding', 'Strong open-source community'], weaknesses: ['Limited enterprise features', 'No Kubernetes management', 'Basic observability'] },
    { name: 'CloudPilot', description: 'Multi-cloud management platform focused on cost optimization and governance', website: 'cloudpilot.eu', market_share: 18, strengths: ['Best-in-class FinOps', 'Multi-cloud visibility', 'Compliance automation'], weaknesses: ['No CI/CD features', 'Weak developer tooling', 'Complex pricing model'] },
    { name: 'KubeForge', description: 'Kubernetes-native platform engineering tool with GitOps-first approach', website: 'kubeforge.io', market_share: 10, strengths: ['Deep Kubernetes expertise', 'GitOps-native', 'Active CNCF contributor'], weaknesses: ['Kubernetes-only focus', 'Small sales team', 'Limited non-K8s infrastructure support'] },
  ],

  events: [
    { name: 'KubeCon Europe 2026', type: 'conference', description: 'The flagship Cloud Native Computing Foundation conference with 12,000+ attendees from across the cloud-native ecosystem', location: 'RAI Amsterdam', city: 'Amsterdam', country: 'Netherlands', date_start: daysFromNow(16), date_end: daysFromNow(19), expected_attendees: 12500, target_audience_match: 95, estimated_roi: 520, estimated_leads: 110, networking_value: 97, cost: 35000, topics: ['Kubernetes', 'Cloud Native', 'Platform Engineering', 'Observability', 'Service Mesh'], status: 'confirmed', priority_score: 99 },
    { name: 'DevOps Days Amsterdam', type: 'conference', description: 'Community-driven DevOps conference focused on practical engineering culture, automation, and collaboration', location: 'Pakhuis de Zwijger', city: 'Amsterdam', country: 'Netherlands', date_start: daysFromNow(42), date_end: daysFromNow(43), expected_attendees: 800, target_audience_match: 90, estimated_roi: 340, estimated_leads: 40, networking_value: 88, cost: 9500, topics: ['DevOps Culture', 'Automation', 'CI/CD', 'SRE', 'Platform Engineering'], status: 'confirmed', priority_score: 88 },
    { name: 'AWS Summit Berlin', type: 'summit', description: 'AWS flagship European summit for cloud professionals, architects, and decision-makers', location: 'Station Berlin', city: 'Berlin', country: 'Germany', date_start: daysFromNow(58), date_end: daysFromNow(59), expected_attendees: 5000, target_audience_match: 78, estimated_roi: 280, estimated_leads: 55, networking_value: 82, cost: 15000, topics: ['Cloud Architecture', 'Serverless', 'Multi-cloud', 'AI/ML Infrastructure', 'Cost Optimization'], status: 'evaluating', priority_score: 79 },
  ],

  personas: [
    { name: 'Alex — The Engineering VP', description: 'Senior engineering leader responsible for developer productivity, platform strategy, and engineering headcount ROI', demographics: { age: '38-50', education: 'MSc Computer Science or equivalent', income: '€160K-€240K', location: 'European tech hub' }, psychographics: { motivation: 'Ship faster without sacrificing reliability', decision_style: 'Data-driven, values engineering culture', risk_tolerance: 'Moderate — needs proven track record and customer references' }, pain_points: ['Developer velocity slowing as team grows', 'Too many disconnected DevOps tools', 'Cloud costs growing faster than revenue', 'Hiring and retaining platform engineers is difficult'], goals: ['Reduce time-to-production by 50%', 'Consolidate DevOps toolchain', 'Improve developer satisfaction scores', 'Achieve predictable cloud spend'], preferred_channels: ['LinkedIn', 'Tech blogs', 'Peer recommendations', 'Industry conferences'] },
    { name: 'Dana — The DevOps Team Lead', description: 'Hands-on technical leader managing the CI/CD pipeline, infrastructure automation, and on-call rotation', demographics: { age: '30-40', education: 'BSc/MSc Software Engineering or self-taught', income: '€90K-€130K', location: 'Remote-first company' }, psychographics: { motivation: 'Automate everything, reduce toil and manual ops', decision_style: 'Technical-first, evaluates via proof-of-concept', risk_tolerance: 'Higher — willing to pilot new tools if they solve real pain' }, pain_points: ['YAML sprawl across multiple config systems', 'Slow CI/CD pipelines blocking developers', 'Incident fatigue from poor observability', 'Context-switching between 6+ tools daily'], goals: ['Sub-5-minute build-to-deploy pipeline', 'Single pane of glass for all infrastructure', 'Self-service developer platform', 'Reduce mean-time-to-recovery to under 10 minutes'], preferred_channels: ['GitHub', 'Dev.to', 'Hacker News', 'Technical webinars', 'Slack communities'] },
    { name: 'Chris — The Cloud Architect', description: 'Senior technical individual contributor who designs cloud architectures, evaluates tools, and sets infrastructure standards', demographics: { age: '35-45', education: 'Cloud certifications (AWS SA Pro, CKA, GCP Pro)', income: '€110K-€170K', location: 'Hybrid — 2-3 days office' }, psychographics: { motivation: 'Design elegant, scalable, and cost-efficient systems', decision_style: 'Deep technical evaluation, PoC-driven', risk_tolerance: 'Low for production — demands stability guarantees and SLAs' }, pain_points: ['Multi-cloud complexity and vendor lock-in', 'Infrastructure drift between environments', 'Security and compliance requirements slowing delivery', 'Lack of standardized developer platform'], goals: ['Implement GitOps across all environments', 'Achieve consistent multi-cloud deployments', 'Reduce infrastructure drift to zero', 'Build a reusable platform blueprint'], preferred_channels: ['Technical documentation', 'GitHub repos', 'CNCF ecosystem', 'Architecture conferences', 'Stack Overflow'] },
  ],

  products: [
    { name: 'CloudNexus Control Plane', description: 'Unified cloud infrastructure management platform with multi-cloud Kubernetes orchestration, automated scaling, and real-time observability across AWS, Azure, and GCP', category: 'Platform', status: 'active', price_range: '€48K-€180K/year', target_audience: 'Engineering teams with 20+ developers', key_features: ['Multi-cloud Kubernetes management', 'Automated cluster scaling', 'Real-time observability dashboards', 'Policy-as-code governance', 'Cost allocation and FinOps'], competitive_advantages: ['60% faster deployments', 'Single control plane for 3+ clouds', '99.99% platform uptime SLA'] },
    { name: 'CloudNexus Pipelines', description: 'AI-powered CI/CD platform with intelligent test selection, parallel execution, and progressive delivery including canary and blue-green deployments', category: 'Module', status: 'active', price_range: '€18K-€72K/year', target_audience: 'DevOps and platform engineering teams', key_features: ['AI-powered test selection', 'Parallel pipeline execution', 'Canary and blue-green deployments', 'GitOps-native workflow', 'Build cache optimization'], competitive_advantages: ['Sub-3-minute average build time', '40% reduction in CI costs', 'Zero-config progressive delivery'] },
    { name: 'CloudNexus Shield', description: 'Cloud security and compliance automation platform with vulnerability scanning, runtime protection, and continuous compliance for SOC 2, ISO 27001, and GDPR', category: 'Add-on', status: 'active', price_range: '€12K-€48K/year', target_audience: 'Security-conscious engineering organizations', key_features: ['Container vulnerability scanning', 'Runtime threat detection', 'Compliance-as-code (SOC 2, ISO 27001, GDPR)', 'Supply chain security', 'Secrets management'], competitive_advantages: ['Automated compliance evidence collection', 'Real-time security posture scoring', 'Shift-left security in CI pipeline'] },
  ],

  strategicObjectives: [
    { name: 'European Cloud Platform Market Leadership', description: 'Become the #1 independent cloud platform for mid-market and enterprise engineering teams in Europe by 2027', category: 'growth', target_value: 20, current_value: 14, unit: 'market_share_%', priority: 'high' },
    { name: 'ARR Growth Target', description: 'Achieve €18M ARR by end of 2026 through new customer acquisition and expansion revenue', category: 'revenue', target_value: 18000000, current_value: 12600000, unit: 'EUR', priority: 'critical' },
    { name: 'Net Revenue Retention', description: 'Maintain net revenue retention above 130% through upsell, cross-sell, and platform expansion', category: 'customer_success', target_value: 130, current_value: 127, unit: '%', priority: 'high' },
    { name: 'Developer Community Growth', description: 'Grow active developer community to 25,000 members through open-source contributions, events, and content', category: 'community', target_value: 25000, current_value: 16800, unit: 'members', priority: 'medium' },
  ],

  organizationEntities: [
    { name: 'Engineering & Product', type: 'department', description: 'Core platform development, AI/ML engineering, product management, and developer experience' },
    { name: 'Sales & Revenue', type: 'department', description: 'Enterprise sales, solutions engineering, partnerships, and channel development' },
    { name: 'Marketing & Developer Relations', type: 'department', description: 'Brand, content, demand generation, events, developer advocacy, and community management' },
    { name: 'Customer Success & Support', type: 'department', description: 'Onboarding, technical support, account management, and professional services' },
    { name: 'Cloud Infrastructure & SRE', type: 'department', description: 'Internal platform operations, site reliability engineering, and security operations' },
  ],

  // Finance data
  financeCustomers: [
    { name: 'TechVenture Amsterdam', email: 'finance@techventure.nl', phone: '+31 20 555 1200', address: 'Herengracht 420', city: 'Amsterdam', postal_code: '1017 BZ', country: 'Netherlands', contact_person: 'Sander van Dijk', kvk_number: '71234567', btw_number: 'NL812345678B01', payment_terms: 30, status: 'active' },
    { name: 'ScaleUp Berlin', email: 'accounts@scaleup-berlin.de', phone: '+49 30 880 2200', address: 'Torstrasse 89', city: 'Berlin', postal_code: '10119', country: 'Germany', contact_person: 'Lena Hoffmann', kvk_number: '', btw_number: 'DE298765432', payment_terms: 30, status: 'active' },
    { name: 'FinTech Brussels', email: 'ap@fintechbrussels.be', phone: '+32 2 620 5500', address: 'Avenue Louise 251', city: 'Brussels', postal_code: '1050', country: 'Belgium', contact_person: 'Antoine Leroy', kvk_number: '', btw_number: 'BE0765432198', payment_terms: 30, status: 'active' },
    { name: 'DataStream Vienna', email: 'billing@datastream.at', phone: '+43 1 515 4400', address: 'Mariahilfer Strasse 78', city: 'Vienna', postal_code: '1070', country: 'Austria', contact_person: 'Dr. Katarina Novak', kvk_number: '', btw_number: 'ATU63456789', payment_terms: 45, status: 'active' },
    { name: 'Nordic Cloud Solutions', email: 'faktura@nordiccloud.se', phone: '+46 8 555 1800', address: 'Sveavagen 44', city: 'Stockholm', postal_code: '111 34', country: 'Sweden', contact_person: 'Maja Lindqvist', kvk_number: '', btw_number: 'SE556789012301', payment_terms: 30, status: 'active' },
    { name: 'RapidScale Dublin', email: 'accounts@rapidscale.ie', phone: '+353 1 525 6600', address: 'Grand Canal Dock', city: 'Dublin', postal_code: 'D04 V2N9', country: 'Ireland', contact_person: 'Emma O\'Brien', kvk_number: '', btw_number: 'IE9S87654L', payment_terms: 30, status: 'active' },
    { name: 'CloudNine Payments', email: 'finance@cloudnine.nl', phone: '+31 10 440 3300', address: 'Coolsingel 120', city: 'Rotterdam', postal_code: '3011 AG', country: 'Netherlands', contact_person: 'Pieter de Groot', kvk_number: '69876543', btw_number: 'NL823456789B01', payment_terms: 30, status: 'active' },
    { name: 'CyberForge Warsaw', email: 'rozliczenia@cyberforge.pl', phone: '+48 22 520 7700', address: 'Zlota 59', city: 'Warsaw', postal_code: '00-120', country: 'Poland', contact_person: 'Tomasz Kowalski', kvk_number: '', btw_number: 'PL5261234567', payment_terms: 30, status: 'active' },
  ],

  financeSuppliers: [
    { name: 'AWS Europe', email: 'aws-billing@amazon.com', phone: '+353 1 800 7890', address: 'Burlington Road', city: 'Dublin', postal_code: 'D04 HH21', country: 'Ireland', contact_person: 'Cloud Services Team', kvk_number: '', btw_number: 'IE9876543W', payment_terms: 30, status: 'active' },
    { name: 'Hetzner Cloud', email: 'billing@hetzner.com', phone: '+49 9831 505 0', address: 'Industriestrasse 25', city: 'Gunzenhausen', postal_code: '91710', country: 'Germany', contact_person: 'Cloud Infrastructure Team', kvk_number: '', btw_number: 'DE812871812', payment_terms: 30, status: 'active' },
    { name: 'DevMarketing Agency', email: 'invoices@devmarketing.nl', phone: '+31 20 555 0400', address: 'Keizersgracht 62', city: 'Amsterdam', postal_code: '1015 CS', country: 'Netherlands', contact_person: 'Roos van Leeuwen', kvk_number: '72345678', btw_number: 'NL834567890B01', payment_terms: 14, status: 'active' },
    { name: 'Elastic Observability', email: 'billing@elastic.co', phone: '+31 20 400 5500', address: 'Keizersgracht 281', city: 'Amsterdam', postal_code: '1016 ED', country: 'Netherlands', contact_person: 'Enterprise Accounts', kvk_number: '75678901', btw_number: 'NL856789012B01', payment_terms: 30, status: 'active' },
    { name: 'TechTalent Partners', email: 'finance@techtalent.eu', phone: '+31 30 555 0800', address: 'Maliebaan 72', city: 'Utrecht', postal_code: '3581 CV', country: 'Netherlands', contact_person: 'Recruitment Services', kvk_number: '78901234', btw_number: 'NL867890123B01', payment_terms: 14, status: 'active' },
  ],

  financeInvoices: [
    { invoice_type: 'sales', entity_name: 'TechVenture Amsterdam', description: 'CloudNexus Control Plane — Annual Enterprise License Q1 2026', subtotal: 52000, tax_amount: 10920, total_amount: 62920, status: 'paid', days_offset: -58 },
    { invoice_type: 'sales', entity_name: 'ScaleUp Berlin', description: 'CloudNexus Pipelines — Annual License + Onboarding', subtotal: 42000, tax_amount: 7980, total_amount: 49980, status: 'paid', days_offset: -42 },
    { invoice_type: 'sales', entity_name: 'DataStream Vienna', description: 'CloudNexus Control Plane — Enterprise License + Shield Add-on', subtotal: 72000, tax_amount: 14400, total_amount: 86400, status: 'pending', days_offset: -12 },
    { invoice_type: 'sales', entity_name: 'RapidScale Dublin', description: 'CloudNexus Pipelines — Annual Subscription', subtotal: 36000, tax_amount: 7560, total_amount: 43560, status: 'pending', days_offset: -8 },
    { invoice_type: 'sales', entity_name: 'CloudNine Payments', description: 'CloudNexus Control Plane — License + Professional Services', subtotal: 58000, tax_amount: 12180, total_amount: 70180, status: 'paid', days_offset: -85 },
    { invoice_type: 'sales', entity_name: 'FinTech Brussels', description: 'CloudNexus Shield — Compliance Module Pilot', subtotal: 15000, tax_amount: 3150, total_amount: 18150, status: 'overdue', days_offset: -70 },
    { invoice_type: 'sales', entity_name: 'Nordic Cloud Solutions', description: 'Consulting — Cloud Architecture Assessment', subtotal: 14500, tax_amount: 3045, total_amount: 17545, status: 'paid', days_offset: -28 },
    { invoice_type: 'sales', entity_name: 'CyberForge Warsaw', description: 'CloudNexus Pipelines — Quarterly License', subtotal: 12000, tax_amount: 2760, total_amount: 14760, status: 'pending', days_offset: -5 },
    { invoice_type: 'purchase', entity_name: 'AWS Europe', description: 'Cloud Infrastructure — Multi-Region Hosting Q1 2026', subtotal: 24500, tax_amount: 5145, total_amount: 29645, status: 'paid', days_offset: -30 },
    { invoice_type: 'purchase', entity_name: 'Hetzner Cloud', description: 'Dedicated Bare-Metal Servers — CI/CD Build Farm', subtotal: 6800, tax_amount: 1292, total_amount: 8092, status: 'paid', days_offset: -45 },
    { invoice_type: 'purchase', entity_name: 'DevMarketing Agency', description: 'KubeCon Europe 2026 — Campaign Design & Booth Collateral', subtotal: 18000, tax_amount: 3780, total_amount: 21780, status: 'pending', days_offset: -14 },
    { invoice_type: 'purchase', entity_name: 'TechTalent Partners', description: 'Senior Platform Engineer Recruitment — 2 placements', subtotal: 28000, tax_amount: 5880, total_amount: 33880, status: 'paid', days_offset: -55 },
    { invoice_type: 'purchase', entity_name: 'Elastic Observability', description: 'Elastic Cloud — Observability Stack Annual License', subtotal: 9600, tax_amount: 2016, total_amount: 11616, status: 'paid', days_offset: -20 },
    { invoice_type: 'sales', entity_name: 'TechVenture Amsterdam', description: 'CloudNexus Shield — Security Add-on Module', subtotal: 24000, tax_amount: 5040, total_amount: 29040, status: 'draft', days_offset: 0 },
    { invoice_type: 'purchase', entity_name: 'AWS Europe', description: 'Cloud Infrastructure — Multi-Region Hosting Q2 2026', subtotal: 26200, tax_amount: 5502, total_amount: 31702, status: 'draft', days_offset: 0 },
  ],

  financeBudgets: [
    { category: 'Cloud Infrastructure & Hosting', budgeted_amount: 120000, actual_amount: 92400 },
    { category: 'Marketing & Events', budgeted_amount: 145000, actual_amount: 98500 },
    { category: 'Research & Development', budgeted_amount: 420000, actual_amount: 335000 },
    { category: 'Personnel & Recruitment', budgeted_amount: 1100000, actual_amount: 840000 },
    { category: 'Security & Compliance', budgeted_amount: 55000, actual_amount: 38000 },
    { category: 'Sales & Partnerships', budgeted_amount: 95000, actual_amount: 67000 },
  ],

  financeGoals: [
    { goal: 'Achieve €18M ARR', category: 'revenue', target_value: 18000000, current_value: 12600000, unit: 'EUR', status: 'on_track' },
    { goal: 'Maintain gross margin above 80%', category: 'profitability', target_value: 80, current_value: 82, unit: '%', status: 'achieved' },
    { goal: 'Reduce customer acquisition cost by 25%', category: 'efficiency', target_value: 25, current_value: 18, unit: '%', status: 'on_track' },
    { goal: 'Close Series B at €20M valuation', category: 'funding', target_value: 20000000, current_value: 0, unit: 'EUR', status: 'in_progress' },
  ],

  yearPlanName: 'CloudNexus Technologies — Financial Plan 2026',
};
