// src/services/demo-agent/templates/manufacturing.template.ts
import type { IndustryTemplate } from '../types';
import { daysFromNow } from './base-template';

export const manufacturingTemplate: IndustryTemplate = {
  industry: 'manufacturing',

  brand: {
    name: 'Apex Industries',
    tagline: 'Precision Engineering, Global Scale',
    mission: 'To empower manufacturers worldwide with intelligent automation, predictive analytics, and connected factory solutions that drive operational excellence and sustainable growth.',
    description: 'Apex Industries is a leading smart manufacturing technology company providing AI-powered predictive maintenance, digital twin platforms, IoT sensor networks, and supply chain optimization solutions for precision engineering and industrial operations across Europe.',
    tone_attributes: ['Authoritative', 'Precise', 'Quality-driven', 'Innovation-forward'],
    primary_color: '#EF4444',
    secondary_color: '#DC2626',
    usps: ['99.7% predictive maintenance accuracy', 'Real-time IoT sensor integration across 10,000+ endpoints', '32% reduction in unplanned downtime', 'Full Industry 4.0 digital twin platform'],
    brand_values: ['Precision', 'Reliability', 'Innovation', 'Sustainability', 'Operational excellence'],
    audiences: ['Plant managers', 'VP Operations', 'Supply chain directors', 'Manufacturing engineers'],
    industries: ['Manufacturing', 'Precision engineering', 'Automotive', 'Aerospace', 'Semiconductors'],
    messaging_dos: 'Use data-driven metrics and ROI evidence. Emphasize uptime, throughput, and quality yields. Reference industry standards (ISO, Six Sigma). Speak with authority on smart manufacturing and Industry 4.0 transformation.',
    messaging_donts: 'Never oversimplify complex manufacturing processes. Avoid consumer-grade technology language. Do not minimize safety and compliance requirements.',
    preferred_vocabulary: ['predictive maintenance', 'digital twin', 'smart factory', 'Industry 4.0', 'operational excellence', 'throughput optimization', 'OEE', 'supply chain resilience'],
    banned_phrases: ['set it and forget it', 'plug and play', 'one size fits all'],
    voice_name: 'Apex Industrial Authority',
    voice_description: 'Authoritative and precise. Uses engineering-grade language with clear technical depth. Balances innovation messaging with proven reliability and industrial-scale credibility.',
  },

  agentTasks: {
    social_task: 'Creating thought leadership content about predictive maintenance ROI for #Industry40 and #SmartManufacturing communities',
    email_task: 'A/B testing nurture sequence for VP Operations — personalized case studies by plant size and vertical',
    ads_task: 'Optimizing Google Ads for "predictive maintenance platform" and "smart factory solutions" keywords',
    analytics_task: 'Analyzing conversion funnel for plant managers — 38% increase in pilot program requests detected',
    orchestrator_task: 'Coordinating campaign launch for Hannover Messe 2026 lead generation across all channels',
  },

  leads: [
    { name: 'Pieter van Dijk', email: 'p.vandijk@asml.com', company: 'ASML', title: 'VP Operations — EUV Division', composite_score: 96, stage: 'sql', conversion_probability: 0.91, predicted_value: 420000, hot_signals: ['Requested enterprise pilot program', 'Downloaded digital twin architecture whitepaper', 'Visited pricing 6x'], cold_signals: [], source: 'Hannover Messe', tags: ['enterprise', 'semiconductor', 'high-value'], next_best_action: 'Schedule executive briefing with C-suite at Veldhoven HQ', intent_level: 'very_high', buying_stage: 'evaluation' },
    { name: 'Rajesh Sharma', email: 'r.sharma@tatasteel-ij.nl', company: 'Tata Steel IJmuiden', title: 'Plant Manager — Hot Strip Mill', composite_score: 91, stage: 'sql', conversion_probability: 0.84, predicted_value: 310000, hot_signals: ['Attended predictive maintenance webinar', 'Engaged with 4 case studies', 'Connected on LinkedIn'], cold_signals: [], source: 'Webinar', tags: ['enterprise', 'steel', 'heavy-industry'], next_best_action: 'Send ROI calculator customized for continuous process manufacturing', intent_level: 'high', buying_stage: 'evaluation' },
    { name: 'Dr. Anke Hoffmann', email: 'a.hoffmann@philips-mfg.nl', company: 'Philips Manufacturing', title: 'Director of Innovation — Factory Automation', composite_score: 88, stage: 'mql', conversion_probability: 0.73, predicted_value: 265000, hot_signals: ['Downloaded IoT sensor integration guide', 'Opened 9 emails this month'], cold_signals: ['Budget cycle in Q3'], source: 'Content Download', tags: ['enterprise', 'electronics', 'innovation-leader'], next_best_action: 'Invite to private Industry 4.0 roundtable event', intent_level: 'high', buying_stage: 'consideration' },
    { name: 'Lars Eriksson', email: 'l.eriksson@volvo-trucks.se', company: 'Volvo Trucks', title: 'Head of Manufacturing Technology', composite_score: 85, stage: 'mql', conversion_probability: 0.67, predicted_value: 350000, hot_signals: ['Visited product pages 7x', 'Submitted contact form for demo'], cold_signals: ['Long procurement cycle — 9 months'], source: 'Organic Search', tags: ['enterprise', 'automotive', 'nordic'], next_best_action: 'Send Nordic automotive manufacturing success stories', intent_level: 'medium', buying_stage: 'consideration' },
    { name: 'Sophie Lemaire', email: 's.lemaire@airbus-ops.fr', company: 'Airbus Operations', title: 'Supply Chain Director — A320 Programme', composite_score: 93, stage: 'sql', conversion_probability: 0.86, predicted_value: 480000, hot_signals: ['Requested supply chain optimization pilot', 'Downloaded technical architecture docs', 'COO referral'], cold_signals: [], source: 'Partner Referral', tags: ['enterprise', 'aerospace', 'strategic-account'], next_best_action: 'Arrange technical deep-dive with engineering team at Toulouse facility', intent_level: 'very_high', buying_stage: 'decision' },
    { name: 'Thomas Gruber', email: 't.gruber@siemens-energy.de', company: 'Siemens Energy', title: 'Senior Manufacturing Engineer', composite_score: 79, stage: 'mql', conversion_probability: 0.55, predicted_value: 185000, hot_signals: ['Engaged with predictive maintenance content', 'Attended product demo'], cold_signals: ['Decision requires management board approval'], source: 'LinkedIn Ad', tags: ['enterprise', 'energy', 'technical-buyer'], next_best_action: 'Share Siemens-scale plant case study with ROI metrics', intent_level: 'medium', buying_stage: 'awareness' },
    { name: 'Katrien Maes', email: 'k.maes@umicore.be', company: 'Umicore', title: 'VP Manufacturing Operations', composite_score: 82, stage: 'mql', conversion_probability: 0.62, predicted_value: 225000, hot_signals: ['Attended 2 webinars on quality control automation', 'Downloaded comparison guide'], cold_signals: ['Evaluating 3 vendors'], source: 'LinkedIn', tags: ['enterprise', 'materials', 'belgium'], next_best_action: 'Send competitive differentiation deck for process manufacturing', intent_level: 'medium', buying_stage: 'evaluation' },
    { name: 'Marco Visser', email: 'm.visser@daf-trucks.nl', company: 'DAF Trucks', title: 'Director of Smart Factory Initiatives', composite_score: 76, stage: 'lead', conversion_probability: 0.44, predicted_value: 195000, hot_signals: ['Downloaded AI in manufacturing report'], cold_signals: ['Early research phase'], source: 'Content Marketing', tags: ['enterprise', 'automotive', 'netherlands'], next_best_action: 'Enroll in monthly smart manufacturing innovation newsletter', intent_level: 'low', buying_stage: 'awareness' },
    { name: 'Helena Virtanen', email: 'h.virtanen@wartsila.fi', company: 'W\u00e4rtsil\u00e4', title: 'Head of Digital Manufacturing', composite_score: 70, stage: 'lead', conversion_probability: 0.38, predicted_value: 175000, hot_signals: ['Visited integration documentation'], cold_signals: ['Technical evaluation only', 'No budget allocated yet'], source: 'Google Ads', tags: ['enterprise', 'marine-energy', 'finland'], next_best_action: 'Send technical integration guide for maritime manufacturing', intent_level: 'low', buying_stage: 'awareness' },
    { name: 'Jan Kowalski', email: 'j.kowalski@solaris-bus.pl', company: 'Solaris Bus & Coach', title: 'Chief Operations Officer', composite_score: 87, stage: 'mql', conversion_probability: 0.70, predicted_value: 210000, hot_signals: ['Watched 3 customer testimonial videos', 'Requested EU pricing'], cold_signals: ['Polish market entry required'], source: 'Webinar', tags: ['enterprise', 'automotive', 'poland'], next_best_action: 'Connect with Central Europe sales team for localized demo', intent_level: 'high', buying_stage: 'consideration' },
  ],

  campaigns: [
    { name: 'Industry 4.0 Transformation Program', description: 'Multi-channel campaign educating manufacturing executives on the full Industry 4.0 transformation journey — from IoT deployment to AI-driven optimization', objective: 'awareness', status: 'active', budget_total: 65000, budget_spent: 41200, days_remaining: 22, roi: 380, conversions: 142, ai_managed: true, performance_score: 93 },
    { name: 'Predictive Maintenance ROI Campaign', description: 'Targeted campaign showcasing predictive maintenance cost savings with interactive ROI calculators and customer case studies', objective: 'lead_generation', status: 'active', budget_total: 40000, budget_spent: 26800, days_remaining: 28, roi: 520, conversions: 98, ai_managed: true, performance_score: 96 },
    { name: 'Smart Factory Summit 2026', description: 'Pre-event, on-site, and post-event campaign for the Smart Factory Summit in Rotterdam', objective: 'lead_generation', status: 'active', budget_total: 50000, budget_spent: 31500, days_remaining: 15, roi: 410, conversions: 167, ai_managed: false, performance_score: 94 },
    { name: 'Supply Chain Resilience Webinar Series', description: 'Monthly webinar series on building resilient, AI-optimized supply chains for European manufacturers', objective: 'thought_leadership', status: 'active', budget_total: 18000, budget_spent: 11400, days_remaining: 55, roi: 340, conversions: 186, ai_managed: false, performance_score: 90 },
    { name: 'Digital Twin Enterprise Nurture', description: 'Long-term nurture campaign targeting VP Operations and plant managers with digital twin use cases and business impact analysis', objective: 'nurture', status: 'active', budget_total: 22000, budget_spent: 14300, days_remaining: 40, roi: 460, conversions: 52, ai_managed: true, performance_score: 91 },
  ],

  content: [
    { title: 'How Predictive Maintenance Saved a European Steel Mill €2.4M in One Year', body: 'Discover how AI-powered predictive maintenance reduced unplanned downtime by 42% and extended critical asset life by 3 years at a major European steel manufacturing facility.', content_type: 'case_study', channels: ['email', 'linkedin', 'blog'], status: 'published', tags: ['case-study', 'predictive-maintenance', 'ROI'], performance: { impressions: 28700, clicks: 3420, shares: 512, conversions: 84 } },
    { title: 'The Complete Guide to Industry 4.0 Implementation', body: 'A comprehensive roadmap covering IoT sensor deployment, edge computing architecture, digital twin integration, and AI-driven optimization for modern manufacturing operations.', content_type: 'whitepaper', channels: ['email', 'linkedin'], status: 'published', tags: ['Industry-4.0', 'guide', 'digital-transformation'], performance: { impressions: 19500, clicks: 2180, shares: 367, conversions: 112 } },
    { title: 'Digital Twins in Manufacturing: From Concept to Production Value', body: 'Learn how leading manufacturers are deploying digital twins to simulate production scenarios, optimize throughput, and reduce commissioning time by up to 60%.', content_type: 'blog_post', channels: ['blog', 'linkedin', 'email'], status: 'published', tags: ['digital-twin', 'thought-leadership', 'innovation'], performance: { impressions: 31200, clicks: 2750, shares: 423, conversions: 71 } },
    { title: 'Supply Chain Resilience in a Post-Disruption World', body: 'How European manufacturers are leveraging AI-powered supply chain analytics to build resilience, diversify sourcing, and reduce lead time variability by 35%.', content_type: 'blog_post', channels: ['blog', 'linkedin', 'twitter'], status: 'published', tags: ['supply-chain', 'resilience', 'AI'] },
    { title: 'Lean Manufacturing Meets Artificial Intelligence: The Next Frontier', body: 'Explore how AI augments lean principles to achieve new levels of waste reduction, quality improvement, and throughput optimization in smart factory environments.', content_type: 'blog_post', channels: ['blog', 'linkedin'], status: 'published', tags: ['lean-manufacturing', 'AI', 'operational-excellence'], performance: { impressions: 22400, clicks: 1890, shares: 298, conversions: 53 } },
    { title: 'ROI Calculator: Predictive Maintenance for Your Plant', body: 'Interactive tool showing the financial impact of predictive maintenance based on plant size, asset count, current downtime costs, and industry vertical.', content_type: 'interactive', channels: ['email', 'linkedin'], status: 'published', tags: ['ROI', 'calculator', 'lead-magnet'], performance: { impressions: 15600, clicks: 2340, shares: 187, conversions: 96 } },
    { title: 'Webinar: Quality Control Automation — Zero-Defect Manufacturing', body: 'Join our panel of manufacturing experts as they discuss machine vision, in-line quality inspection, and the path to zero-defect production using AI.', content_type: 'webinar', channels: ['email', 'linkedin', 'facebook'], status: 'published', tags: ['webinar', 'quality-control', 'automation'], performance: { impressions: 12800, clicks: 1560, shares: 234, conversions: 67 } },
    { title: 'Infographic: The State of Smart Manufacturing in Europe 2026', body: 'Visual overview of Industry 4.0 adoption rates, IoT investment trends, and digital maturity levels across European manufacturing sectors.', content_type: 'infographic', channels: ['linkedin', 'twitter', 'instagram'], status: 'published', tags: ['infographic', 'market-data', 'europe'], performance: { impressions: 41500, clicks: 3890, shares: 678, conversions: 45 } },
    { title: 'How to Build a Business Case for Smart Factory Investment', body: 'Step-by-step guide for manufacturing leaders on building a compelling business case for Industry 4.0 investment, including OEE improvement frameworks and stakeholder alignment.', content_type: 'guide', channels: ['email', 'blog'], status: 'scheduled', tags: ['business-case', 'smart-factory', 'leadership'] },
    { title: 'Video: Customer Success Story — ASML EUV Line Optimization', body: 'Watch how ASML improved Overall Equipment Effectiveness by 18% with Apex Industries\' predictive maintenance and digital twin platform.', content_type: 'video', channels: ['youtube', 'linkedin', 'email'], status: 'scheduled', tags: ['video', 'customer-story', 'testimonial'] },
    { title: 'Edge Computing in Manufacturing: Processing Data Where It Matters', body: 'How Apex Industries bridges the gap between shop-floor IoT sensors and enterprise analytics with edge computing for real-time decision-making.', content_type: 'blog_post', channels: ['blog', 'linkedin'], status: 'draft', tags: ['edge-computing', 'IoT', 'real-time-analytics'] },
    { title: 'Social Post: Hannover Messe Preview', body: 'We\'re excited to announce our presence at Hannover Messe 2026! Visit Hall 17, Stand D42 for live demos of our new Digital Twin Platform.', content_type: 'social_post', channels: ['linkedin', 'twitter', 'facebook'], status: 'scheduled', tags: ['event', 'hannover-messe', 'announcement'] },
    { title: 'Email: Monthly Smart Manufacturing Digest', body: 'Curated monthly newsletter featuring the latest in Industry 4.0, predictive maintenance breakthroughs, and Apex Industries product updates.', content_type: 'newsletter', channels: ['email'], status: 'published', tags: ['newsletter', 'monthly', 'innovation'] },
    { title: 'Podcast: Manufacturing Leaders — Episode 8', body: 'Interview with Pieter van Dijk on scaling predictive maintenance across semiconductor fabrication lines and lessons from ASML\'s Industry 4.0 journey.', content_type: 'podcast', channels: ['spotify', 'linkedin', 'email'], status: 'draft', tags: ['podcast', 'interview', 'thought-leadership'] },
    { title: 'LinkedIn Carousel: 7 OEE Metrics Every Plant Manager Should Track', body: 'Visual guide to the most critical Overall Equipment Effectiveness metrics, from availability and performance rates to quality yield and mean time between failures.', content_type: 'carousel', channels: ['linkedin'], status: 'published', tags: ['carousel', 'OEE', 'plant-manager'], performance: { impressions: 26300, clicks: 2140, shares: 345, conversions: 38 } },
  ],

  competitors: [
    { name: 'FactoryMind', description: 'AI-first manufacturing analytics platform with strong machine learning capabilities', website: 'factorymind.io', market_share: 22, strengths: ['Advanced ML models', 'Modern cloud-native architecture', 'Fast deployment'], weaknesses: ['Limited OT integration', 'Small customer base', 'No on-premise option for air-gapped environments'] },
    { name: 'SmartOps Platform', description: 'Enterprise manufacturing operations platform with deep ERP integration', website: 'smartops-platform.com', market_share: 18, strengths: ['Strong SAP integration', 'Comprehensive MES features', 'Large install base in DACH region'], weaknesses: ['Legacy codebase', 'Slow innovation cycle', 'Complex implementation — 12+ month average'] },
    { name: 'IndustrialIQ', description: 'Industrial IoT specialist focused on sensor networks and edge analytics', website: 'industrialiq.eu', market_share: 14, strengths: ['Best-in-class IoT sensor portfolio', 'Edge computing expertise', 'Strong partnerships with hardware OEMs'], weaknesses: ['No digital twin capability', 'Limited supply chain features', 'Basic reporting and dashboards'] },
    { name: 'ManuTech Pro', description: 'Mid-market manufacturing execution system with quality management focus', website: 'manutechpro.com', market_share: 10, strengths: ['Excellent quality management modules', 'Competitive pricing', 'Good mid-market fit'], weaknesses: ['Cannot scale to enterprise', 'No AI or predictive features', 'Limited international presence'] },
  ],

  events: [
    { name: 'Hannover Messe 2026', type: 'conference', description: 'The world\'s leading industrial technology trade fair with 130,000+ attendees from 75 countries', location: 'Deutsche Messe, Hall 17, Stand D42', city: 'Hannover', country: 'Germany', date_start: daysFromNow(20), date_end: daysFromNow(24), expected_attendees: 130000, target_audience_match: 94, estimated_roi: 520, estimated_leads: 145, networking_value: 97, cost: 48000, topics: ['Industry 4.0', 'Smart Manufacturing', 'IoT', 'Digital Twins', 'Predictive Maintenance'], status: 'confirmed', priority_score: 99 },
    { name: 'Smart Factory Expo Rotterdam', type: 'expo', description: 'Regional smart manufacturing expo showcasing Industry 4.0 solutions for Benelux manufacturers', location: 'Rotterdam Ahoy', city: 'Rotterdam', country: 'Netherlands', date_start: daysFromNow(42), date_end: daysFromNow(43), expected_attendees: 3500, target_audience_match: 89, estimated_roi: 380, estimated_leads: 55, networking_value: 85, cost: 12000, topics: ['Smart Factory', 'Automation', 'Supply Chain', 'Quality Control'], status: 'confirmed', priority_score: 87 },
    { name: 'Industry 4.0 Summit Munich', type: 'summit', description: 'Executive summit for manufacturing transformation leaders featuring peer-to-peer networking and case study presentations', location: 'ICM Munich', city: 'Munich', country: 'Germany', date_start: daysFromNow(65), date_end: daysFromNow(66), expected_attendees: 1800, target_audience_match: 92, estimated_roi: 440, estimated_leads: 40, networking_value: 93, cost: 15000, topics: ['Digital Transformation', 'Predictive Analytics', 'Lean 4.0', 'Workforce Upskilling'], status: 'evaluating', priority_score: 90 },
  ],

  personas: [
    { name: 'Operational Otto — The Plant Manager', description: 'Experienced plant manager responsible for production output, equipment uptime, and workforce safety across a large manufacturing facility', demographics: { age: '45-55', education: 'Mechanical Engineering + MBA', income: '\u20AC140K\u2013\u20AC200K', location: 'Industrial manufacturing region' }, psychographics: { motivation: 'Maximize OEE and eliminate unplanned downtime', decision_style: 'Data-driven, risk-averse, needs proven track record', risk_tolerance: 'Low \u2014 requires pilot program results before full deployment' }, pain_points: ['Unplanned equipment downtime costing \u20AC50K+ per incident', 'Aging workforce and knowledge transfer gaps', 'Siloed data across MES, ERP, and SCADA systems', 'Pressure to reduce costs while maintaining quality'], goals: ['Achieve 90%+ OEE across all production lines', 'Reduce unplanned downtime by 40%', 'Implement predictive maintenance on critical assets'], preferred_channels: ['LinkedIn', 'Email', 'Industry trade shows', 'Peer recommendations'] },
    { name: 'Strategic Simone — The VP Operations', description: 'Senior executive overseeing multi-site manufacturing operations with P&L responsibility and digital transformation mandate', demographics: { age: '42-52', education: 'Industrial Engineering + Executive MBA', income: '\u20AC180K\u2013\u20AC280K', location: 'Corporate HQ or major production site' }, psychographics: { motivation: 'Drive operational excellence and Industry 4.0 transformation at enterprise scale', decision_style: 'Strategic, ROI-focused, consensus-builder across business units', risk_tolerance: 'Moderate \u2014 will invest in proven technology with clear business case' }, pain_points: ['Inconsistent performance across manufacturing sites', 'Difficulty justifying large-scale digital transformation investments', 'Supply chain disruptions and visibility gaps', 'Regulatory compliance across multiple jurisdictions'], goals: ['Standardize smart factory platform across all sites', 'Reduce total manufacturing cost by 20%', 'Build a resilient, data-driven supply chain'], preferred_channels: ['Executive briefings', 'LinkedIn', 'Industry summits', 'Analyst reports'] },
    { name: 'Technical Tobias — The Manufacturing Engineer', description: 'Hands-on engineer evaluating and implementing manufacturing technology solutions on the shop floor', demographics: { age: '30-42', education: 'Mechatronics or Industrial Engineering', income: '\u20AC75K\u2013\u20AC110K', location: 'Production facility' }, psychographics: { motivation: 'Implement cutting-edge technology that demonstrably improves production processes', decision_style: 'Technology-first, detail-oriented, needs to understand architecture and integration', risk_tolerance: 'High \u2014 willing to pilot new solutions and iterate quickly' }, pain_points: ['Integrating new IoT sensors with legacy PLC and SCADA systems', 'Vendor lock-in with proprietary protocols', 'Proving ROI for technology projects to management', 'Data quality and standardization challenges'], goals: ['Deploy digital twins for critical production lines', 'Build a unified data platform from sensor to enterprise', 'Automate quality inspection with machine vision'], preferred_channels: ['Technical documentation', 'Developer forums', 'LinkedIn', 'Trade shows', 'Webinars'] },
  ],

  products: [
    { name: 'Apex Predict', description: 'AI-powered predictive maintenance platform that monitors industrial assets in real-time via IoT sensors, predicts failures before they occur, and recommends optimal maintenance windows', category: 'Platform', status: 'active', price_range: '\u20AC80K\u2013\u20AC350K/year', target_audience: 'Manufacturing plants with 500+ assets', key_features: ['Vibration and thermal anomaly detection', 'Remaining useful life prediction', 'Automated work order generation', 'Integration with SAP PM and IBM Maximo'], competitive_advantages: ['99.7% prediction accuracy', '32% reduction in unplanned downtime', 'ROI within 6 months', 'OPC-UA and MQTT native'] },
    { name: 'Apex Digital Twin', description: 'Real-time digital twin platform for manufacturing operations that creates virtual replicas of production lines, enabling simulation, optimization, and what-if scenario planning', category: 'Platform', status: 'active', price_range: '\u20AC120K\u2013\u20AC500K/year', target_audience: 'Enterprise manufacturers with complex production lines', key_features: ['3D production line visualization', 'Real-time process simulation', 'What-if scenario planning', 'Throughput optimization engine'], competitive_advantages: ['60% faster commissioning', '18% OEE improvement', 'Physics-based simulation models', 'Multi-site deployment'] },
    { name: 'Apex Supply Chain Intelligence', description: 'AI-driven supply chain visibility and optimization module providing end-to-end transparency, demand forecasting, and supplier risk management', category: 'Module', status: 'active', price_range: '\u20AC45K\u2013\u20AC180K/year', target_audience: 'Supply chain directors and procurement teams', key_features: ['Multi-tier supplier visibility', 'AI demand forecasting', 'Supplier risk scoring', 'Inventory optimization'], competitive_advantages: ['35% reduction in lead time variability', 'Real-time disruption alerts', '95% forecast accuracy', 'Integrated with 200+ ERP systems'] },
  ],

  strategicObjectives: [
    { name: 'European Market Leadership', description: 'Become the #1 smart manufacturing platform in Europe by 2027', category: 'growth', target_value: 30, current_value: 21, unit: 'market_share_%', priority: 'critical' },
    { name: 'ARR Growth Target', description: 'Achieve \u20AC28M ARR by end of 2026 through enterprise expansion and new verticals', category: 'revenue', target_value: 28000000, current_value: 19600000, unit: 'EUR', priority: 'critical' },
    { name: 'Customer Retention Excellence', description: 'Maintain net revenue retention above 120% across all product lines', category: 'customer_success', target_value: 120, current_value: 118, unit: 'NRR_%', priority: 'high' },
    { name: 'Product Platform Expansion', description: 'Launch 2 new AI-powered modules (quality vision, energy optimization) in 2026', category: 'product', target_value: 2, current_value: 0, unit: 'modules', priority: 'high' },
  ],

  organizationEntities: [
    { name: 'Product & Engineering', type: 'department', description: 'Core platform development, AI/ML research, IoT firmware, and digital twin engineering' },
    { name: 'Sales & Business Development', type: 'department', description: 'Enterprise sales, strategic accounts, partner channels, and new market expansion across Europe' },
    { name: 'Marketing & Communications', type: 'department', description: 'Brand, content marketing, demand generation, events, and analyst relations' },
    { name: 'Customer Success & Deployment', type: 'department', description: 'Implementation engineering, on-site deployment, training, technical support, and account management' },
    { name: 'Industrial Advisory Board', type: 'advisory', description: 'External panel of manufacturing executives and Industry 4.0 thought leaders guiding product roadmap' },
  ],

  // Finance data
  financeCustomers: [
    { name: 'ASML Holding N.V.', email: 'procurement@asml.com', phone: '+31 40 268 3000', address: 'De Run 6501', city: 'Veldhoven', postal_code: '5504 DR', country: 'Netherlands', contact_person: 'Pieter van Dijk', kvk_number: '17032695', btw_number: 'NL004770014B01', payment_terms: 45, status: 'active' },
    { name: 'Tata Steel IJmuiden', email: 'inkoop@tatasteel-ij.nl', phone: '+31 251 499 111', address: 'Wenckebachstraat 1', city: 'IJmuiden', postal_code: '1951 JZ', country: 'Netherlands', contact_person: 'Rajesh Sharma', kvk_number: '34090587', btw_number: 'NL812017725B01', payment_terms: 30, status: 'active' },
    { name: 'Airbus Operations S.A.S.', email: 'supplier.finance@airbus.com', phone: '+33 5 61 93 33 33', address: 'Route de Bayonne 316', city: 'Toulouse', postal_code: '31060', country: 'France', contact_person: 'Sophie Lemaire', kvk_number: '', btw_number: 'FR82383474814', payment_terms: 60, status: 'active' },
    { name: 'Siemens Energy AG', email: 'accounts.payable@siemens-energy.com', phone: '+49 89 636 00', address: 'Otto-Hahn-Ring 6', city: 'Munich', postal_code: '81739', country: 'Germany', contact_person: 'Thomas Gruber', kvk_number: '', btw_number: 'DE325532142', payment_terms: 45, status: 'active' },
    { name: 'Volvo Trucks AB', email: 'leverantorsreskontra@volvo.com', phone: '+46 31 66 00 00', address: 'Gropegardsgatan 2', city: 'Gothenburg', postal_code: '405 08', country: 'Sweden', contact_person: 'Lars Eriksson', kvk_number: '', btw_number: 'SE556013970401', payment_terms: 30, status: 'active' },
    { name: 'Umicore N.V.', email: 'crediteuren@umicore.com', phone: '+32 2 227 71 11', address: 'Broekstraat 31', city: 'Brussels', postal_code: '1000', country: 'Belgium', contact_person: 'Katrien Maes', kvk_number: '', btw_number: 'BE0401574852', payment_terms: 30, status: 'active' },
    { name: 'DAF Trucks N.V.', email: 'finance@daf.com', phone: '+31 40 214 9111', address: 'Hugo van der Goeslaan 1', city: 'Eindhoven', postal_code: '5643 TW', country: 'Netherlands', contact_person: 'Marco Visser', kvk_number: '17027155', btw_number: 'NL001892581B01', payment_terms: 30, status: 'active' },
    { name: 'Solaris Bus & Coach S.A.', email: 'rozrachunki@solarisbus.com', phone: '+48 61 667 2333', address: 'ul. Obornicka 46', city: 'Bolechowo', postal_code: '62-005', country: 'Poland', contact_person: 'Jan Kowalski', kvk_number: '', btw_number: 'PL7772742492', payment_terms: 30, status: 'active' },
  ],

  financeSuppliers: [
    { name: 'AWS Industrial IoT Services', email: 'billing@amazon.com', phone: '+1 206 266 1000', address: '410 Terry Avenue North', city: 'Seattle', postal_code: '98109', country: 'USA', contact_person: 'IoT Cloud Services Team', kvk_number: '', btw_number: 'US916284946', payment_terms: 30, status: 'active' },
    { name: 'Beckhoff Automation GmbH', email: 'rechnung@beckhoff.com', phone: '+49 5246 963 0', address: 'Huelshorstweg 20', city: 'Verl', postal_code: '33415', country: 'Germany', contact_person: 'Automation Components', kvk_number: '', btw_number: 'DE124850673', payment_terms: 30, status: 'active' },
    { name: 'IndustrialEdge Marketing B.V.', email: 'facturen@industrialedge-mktg.nl', phone: '+31 20 555 0300', address: 'Keizersgracht 520', city: 'Amsterdam', postal_code: '1017 EK', country: 'Netherlands', contact_person: 'Lotte de Boer', kvk_number: '71234567', btw_number: 'NL858901234B01', payment_terms: 14, status: 'active' },
    { name: 'Siemens MindSphere Hosting', email: 'cloud-billing@siemens.com', phone: '+49 89 636 00', address: 'Werner-von-Siemens-Str. 1', city: 'Munich', postal_code: '80333', country: 'Germany', contact_person: 'Cloud Infrastructure', kvk_number: '', btw_number: 'DE129274202', payment_terms: 30, status: 'active' },
    { name: 'OT Talent Partners B.V.', email: 'invoicing@ottalent.nl', phone: '+31 40 555 0400', address: 'Strijp-S, Torenallee 45', city: 'Eindhoven', postal_code: '5617 BA', country: 'Netherlands', contact_person: 'HR & Recruitment Services', kvk_number: '82345678', btw_number: 'NL862345678B01', payment_terms: 14, status: 'active' },
  ],

  financeInvoices: [
    { invoice_type: 'sales', entity_name: 'ASML Holding N.V.', description: 'Apex Predict \u2014 Enterprise License Q1 2026 (EUV Division)', subtotal: 87500, tax_amount: 18375, total_amount: 105875, status: 'paid', days_offset: -55 },
    { invoice_type: 'sales', entity_name: 'Tata Steel IJmuiden', description: 'Apex Predict \u2014 Annual License + IoT Sensor Deployment', subtotal: 72000, tax_amount: 15120, total_amount: 87120, status: 'paid', days_offset: -42 },
    { invoice_type: 'sales', entity_name: 'Airbus Operations S.A.S.', description: 'Apex Supply Chain Intelligence \u2014 Enterprise License A320 Programme', subtotal: 145000, tax_amount: 29000, total_amount: 174000, status: 'pending', days_offset: -18 },
    { invoice_type: 'sales', entity_name: 'Siemens Energy AG', description: 'Apex Digital Twin \u2014 Pilot Program (3 turbine lines)', subtotal: 68000, tax_amount: 12920, total_amount: 80920, status: 'pending', days_offset: -12 },
    { invoice_type: 'sales', entity_name: 'Volvo Trucks AB', description: 'Apex Predict \u2014 Annual License + Training Package', subtotal: 56000, tax_amount: 11200, total_amount: 67200, status: 'paid', days_offset: -85 },
    { invoice_type: 'sales', entity_name: 'Umicore N.V.', description: 'Apex Predict \u2014 Process Manufacturing Module', subtotal: 42000, tax_amount: 8820, total_amount: 50820, status: 'overdue', days_offset: -70 },
    { invoice_type: 'sales', entity_name: 'DAF Trucks N.V.', description: 'Consulting \u2014 Smart Factory Readiness Assessment', subtotal: 18500, tax_amount: 3885, total_amount: 22385, status: 'paid', days_offset: -28 },
    { invoice_type: 'sales', entity_name: 'Solaris Bus & Coach S.A.', description: 'Apex Predict \u2014 Quarterly License + Integration Services', subtotal: 34000, tax_amount: 7140, total_amount: 41140, status: 'pending', days_offset: -8 },
    { invoice_type: 'purchase', entity_name: 'AWS Industrial IoT Services', description: 'Cloud Hosting \u2014 Industrial IoT Infrastructure Q1 2026', subtotal: 32000, tax_amount: 6720, total_amount: 38720, status: 'paid', days_offset: -30 },
    { invoice_type: 'purchase', entity_name: 'Siemens MindSphere Hosting', description: 'Edge Computing Infrastructure \u2014 Co-location Services', subtotal: 14500, tax_amount: 2755, total_amount: 17255, status: 'paid', days_offset: -45 },
    { invoice_type: 'purchase', entity_name: 'IndustrialEdge Marketing B.V.', description: 'Hannover Messe 2026 \u2014 Campaign Design + Stand Materials', subtotal: 22000, tax_amount: 4620, total_amount: 26620, status: 'pending', days_offset: -14 },
    { invoice_type: 'purchase', entity_name: 'OT Talent Partners B.V.', description: 'OT Security Specialist \u2014 6 month contract', subtotal: 48000, tax_amount: 10080, total_amount: 58080, status: 'paid', days_offset: -60 },
    { invoice_type: 'purchase', entity_name: 'Beckhoff Automation GmbH', description: 'Industrial IoT Gateway Hardware \u2014 50 units', subtotal: 37500, tax_amount: 7125, total_amount: 44625, status: 'paid', days_offset: -22 },
    { invoice_type: 'sales', entity_name: 'ASML Holding N.V.', description: 'Apex Digital Twin \u2014 Add-on Module (Lithography Line)', subtotal: 95000, tax_amount: 19950, total_amount: 114950, status: 'draft', days_offset: 0 },
    { invoice_type: 'purchase', entity_name: 'AWS Industrial IoT Services', description: 'Cloud Hosting \u2014 Industrial IoT Infrastructure Q2 2026', subtotal: 34500, tax_amount: 7245, total_amount: 41745, status: 'draft', days_offset: 0 },
  ],

  financeBudgets: [
    { category: 'Cloud & Edge Infrastructure', budgeted_amount: 160000, actual_amount: 124000 },
    { category: 'Marketing & Events', budgeted_amount: 185000, actual_amount: 132000 },
    { category: 'Research & Development', budgeted_amount: 520000, actual_amount: 410000 },
    { category: 'Personnel & Recruitment', budgeted_amount: 1400000, actual_amount: 1080000 },
    { category: 'IoT Hardware & Sensors', budgeted_amount: 95000, actual_amount: 67000 },
    { category: 'Sales & Business Development', budgeted_amount: 140000, actual_amount: 98000 },
  ],

  financeGoals: [
    { goal: 'Achieve \u20AC28M ARR', category: 'revenue', target_value: 28000000, current_value: 19600000, unit: 'EUR', status: 'on_track' },
    { goal: 'Maintain gross margin above 72%', category: 'profitability', target_value: 72, current_value: 74, unit: '%', status: 'achieved' },
    { goal: 'Reduce customer acquisition cost by 18%', category: 'efficiency', target_value: 18, current_value: 12, unit: '%', status: 'on_track' },
    { goal: 'Expand to 50 enterprise manufacturing customers', category: 'growth', target_value: 50, current_value: 34, unit: 'customers', status: 'in_progress' },
  ],

  yearPlanName: 'Apex Industries \u2014 Financial Plan 2026',
};
