// src/services/demo-agent/templates/real-estate.template.ts
import type { IndustryTemplate } from '../types';
import { daysFromNow } from './base-template';

export const realEstateTemplate: IndustryTemplate = {
  industry: 'real-estate',

  brand: {
    name: 'Prestige Properties',
    tagline: 'Luxury Living, Redefined',
    mission: 'To elevate the real estate experience through cutting-edge property technology, bespoke client service, and an unwavering commitment to architectural excellence.',
    description: 'Prestige Properties is a premium real estate and property technology company specializing in luxury residential sales, commercial property management, and immersive virtual tour experiences across Europe\'s most coveted markets.',
    tone_attributes: ['Sophisticated', 'Exclusive', 'Trustworthy', 'Lifestyle-focused'],
    primary_color: '#10B981',
    secondary_color: '#059669',
    usps: ['AI-powered property valuation with 97% accuracy', 'Immersive 3D virtual tours with Matterport integration', 'End-to-end digital transaction management', 'Curated portfolio of 2,000+ premium listings'],
    brand_values: ['Excellence', 'Discretion', 'Innovation', 'Integrity', 'Sustainability'],
    audiences: ['Property developers', 'Real estate investors', 'Luxury home buyers', 'Property managers'],
    industries: ['Real estate', 'Property technology', 'Luxury lifestyle', 'Commercial property'],
    messaging_dos: 'Emphasize exclusivity and lifestyle aspirations. Use elegant, polished language. Highlight technology as an enabler of seamless experiences. Reference market expertise and proven track records.',
    messaging_donts: 'Never use high-pressure sales language. Avoid generic or mass-market phrasing. Do not make guarantees about property value appreciation.',
    preferred_vocabulary: ['curated portfolio', 'bespoke experience', 'prime location', 'architectural distinction', 'investment grade', 'digital concierge'],
    banned_phrases: ['cheap deals', 'bargain prices', 'no money down', 'get rich quick'],
    voice_name: 'Prestige Advisor',
    voice_description: 'Refined and confident. Speaks with the authority of a seasoned market insider while maintaining warmth and approachability. Balances aspirational lifestyle messaging with data-driven market intelligence.',
  },

  agentTasks: {
    social_task: 'Creating cinematic property showcase reels for #LuxuryRealEstate and #PrestigeLiving communities',
    email_task: 'Personalizing property recommendation sequences for high-net-worth investors based on portfolio preferences',
    ads_task: 'Optimizing Google Ads for "luxury apartments Amsterdam" and "premium investment property Europe" keywords',
    analytics_task: 'Analyzing property inquiry conversion funnel — 38% increase in virtual tour bookings detected this quarter',
    orchestrator_task: 'Coordinating cross-channel campaign for MIPIM Cannes 2026 lead generation and brand activation',
  },

  leads: [
    { name: 'Willem van Dijk', email: 'w.vandijk@amsterdamdevelopment.nl', company: 'Amsterdam Development Group', title: 'Chief Executive Officer', composite_score: 96, stage: 'sql', conversion_probability: 0.91, predicted_value: 450000, hot_signals: ['Requested full portfolio presentation', 'Visited pricing 6x in 2 weeks', 'Attended private viewing event'], cold_signals: [], source: 'MIPIM Conference', tags: ['enterprise', 'developer', 'amsterdam'], next_best_action: 'Schedule private portfolio walkthrough with CEO', intent_level: 'very_high', buying_stage: 'decision' },
    { name: 'Charlotte de Graaf', email: 'c.degraaf@bouwfondspartners.nl', company: 'Bouwfonds Investment Partners', title: 'Investment Director', composite_score: 93, stage: 'sql', conversion_probability: 0.87, predicted_value: 680000, hot_signals: ['Downloaded investment returns whitepaper', 'Requested ROI projections for 3 developments', 'Connected via partner referral'], cold_signals: [], source: 'Partner Referral', tags: ['institutional-investor', 'high-value'], next_best_action: 'Send customized investment portfolio with projected yields', intent_level: 'very_high', buying_stage: 'evaluation' },
    { name: 'Maximilian Schneider', email: 'm.schneider@engelvolk-munich.de', company: 'Engel & Schneider Immobilien', title: 'Head of Sales', composite_score: 88, stage: 'mql', conversion_probability: 0.74, predicted_value: 320000, hot_signals: ['Engaged with 8 property listings', 'Attended virtual tour demo', 'Opened every email this month'], cold_signals: ['Decision requires partner approval'], source: 'LinkedIn Ad', tags: ['brokerage', 'germany', 'partnership'], next_best_action: 'Invite to exclusive partner program presentation', intent_level: 'high', buying_stage: 'consideration' },
    { name: 'Sofia Lindqvist', email: 's.lindqvist@nordicproperty.se', company: 'Nordic Property Capital', title: 'Managing Partner', composite_score: 91, stage: 'sql', conversion_probability: 0.83, predicted_value: 520000, hot_signals: ['Requested multi-market analysis', 'Downloaded PropTech integration guide', 'Visited product page 5x'], cold_signals: [], source: 'Webinar', tags: ['fund-manager', 'nordic', 'multi-market'], next_best_action: 'Arrange multi-market investment briefing with analytics team', intent_level: 'very_high', buying_stage: 'evaluation' },
    { name: 'Jean-Pierre Moreau', email: 'jp.moreau@parisresidences.fr', company: 'Paris Luxury Residences', title: 'Director of Acquisitions', composite_score: 85, stage: 'mql', conversion_probability: 0.68, predicted_value: 390000, hot_signals: ['Attended MIPIM side event', 'Watched 4 virtual tour demos'], cold_signals: ['Long due diligence cycle'], source: 'MIPIM Conference', tags: ['luxury', 'france', 'acquisitions'], next_best_action: 'Send Paris market intelligence report with comparable sales', intent_level: 'high', buying_stage: 'consideration' },
    { name: 'Emma van Houten', email: 'e.vanhouten@greenurban.nl', company: 'Green Urban Developments', title: 'Sustainability Director', composite_score: 82, stage: 'mql', conversion_probability: 0.62, predicted_value: 275000, hot_signals: ['Downloaded sustainable building whitepaper', 'Attended green property webinar'], cold_signals: ['Budget cycle aligns with Q3'], source: 'Content Download', tags: ['sustainability', 'development', 'green-building'], next_best_action: 'Share sustainability certification case studies', intent_level: 'medium', buying_stage: 'consideration' },
    { name: 'Alexander Petrov', email: 'a.petrov@balticestates.lv', company: 'Baltic Estates International', title: 'Chief Investment Officer', composite_score: 78, stage: 'mql', conversion_probability: 0.55, predicted_value: 210000, hot_signals: ['Visited property valuation tool page', 'Submitted contact form'], cold_signals: ['Evaluating 3 competing platforms'], source: 'Google Ads', tags: ['baltic', 'investor', 'emerging-market'], next_best_action: 'Send competitive differentiation deck with Baltic market data', intent_level: 'medium', buying_stage: 'awareness' },
    { name: 'Isabella Romano', email: 'i.romano@milanoprime.it', company: 'Milano Prime Realty', title: 'Managing Director', composite_score: 76, stage: 'lead', conversion_probability: 0.48, predicted_value: 340000, hot_signals: ['Downloaded virtual staging brochure'], cold_signals: ['Early research phase', 'No demo requested yet'], source: 'Content Marketing', tags: ['italy', 'luxury', 'residential'], next_best_action: 'Enroll in monthly luxury market insights newsletter', intent_level: 'low', buying_stage: 'awareness' },
    { name: 'Lars Henriksen', email: 'l.henriksen@copenhagenpm.dk', company: 'Copenhagen Property Management', title: 'Operations Director', composite_score: 73, stage: 'lead', conversion_probability: 0.42, predicted_value: 185000, hot_signals: ['Visited property management features page'], cold_signals: ['Technical evaluation only', 'No budget allocated'], source: 'Organic Search', tags: ['property-management', 'denmark', 'operations'], next_best_action: 'Send property management platform demo video', intent_level: 'medium', buying_stage: 'awareness' },
    { name: 'Victoria Blackwell', email: 'v.blackwell@londonestategroup.uk', company: 'London Estate Group', title: 'Head of International Sales', composite_score: 70, stage: 'lead', conversion_probability: 0.38, predicted_value: 410000, hot_signals: ['Attended PropTech Summit session'], cold_signals: ['Brexit-related compliance concerns', 'Long procurement timeline'], source: 'Event', tags: ['uk', 'international', 'prime-london'], next_best_action: 'Connect with UK partnership team for regulatory briefing', intent_level: 'low', buying_stage: 'awareness' },
  ],

  campaigns: [
    { name: 'Luxury Property Launch Event — Amsterdam Canal District', description: 'Exclusive invitation-only launch for 24 waterfront residences in Amsterdam\'s historic canal belt', objective: 'lead_generation', status: 'active', budget_total: 85000, budget_spent: 52000, days_remaining: 22, roi: 520, conversions: 64, ai_managed: true, performance_score: 96 },
    { name: 'Property Investment Webinar Series', description: 'Monthly expert-led webinars on European property investment strategies, yields, and market forecasting', objective: 'thought_leadership', status: 'active', budget_total: 25000, budget_spent: 14800, days_remaining: 40, roi: 380, conversions: 189, ai_managed: true, performance_score: 92 },
    { name: 'Virtual Tour Technology Showcase', description: 'Interactive campaign demonstrating AI-powered 3D virtual tours and digital staging capabilities to brokers and developers', objective: 'product_launch', status: 'active', budget_total: 40000, budget_spent: 27500, days_remaining: 28, roi: 310, conversions: 112, ai_managed: false, performance_score: 89 },
    { name: 'MIPIM Cannes 2026 Brand Activation', description: 'Pre-event, on-site booth, and post-event nurture campaign for the world\'s leading property conference', objective: 'brand_awareness', status: 'active', budget_total: 120000, budget_spent: 78000, days_remaining: 15, roi: 440, conversions: 97, ai_managed: true, performance_score: 94 },
    { name: 'Sustainable Living Developer Outreach', description: 'Targeted campaign connecting with eco-conscious developers and showcasing green building certification support', objective: 'nurture', status: 'active', budget_total: 18000, budget_spent: 9600, days_remaining: 55, roi: 260, conversions: 43, ai_managed: false, performance_score: 87 },
  ],

  content: [
    { title: 'European Luxury Real Estate Market Report 2026', body: 'Comprehensive analysis of luxury residential markets across Amsterdam, Paris, London, and Munich, including price-per-square-metre trends, buyer demographics, and investment yield forecasts.', content_type: 'whitepaper', channels: ['email', 'linkedin', 'blog'], status: 'published', tags: ['market-report', 'luxury', 'europe'], performance: { impressions: 42000, clicks: 3850, shares: 612, conversions: 134 } },
    { title: '7 Property Investment Metrics Every Investor Must Track in 2026', body: 'From cap rates and gross rental yields to vacancy risk scores and ESG compliance ratings, these are the KPIs separating savvy investors from the rest.', content_type: 'blog_post', channels: ['blog', 'linkedin', 'twitter'], status: 'published', tags: ['investment', 'KPIs', 'thought-leadership'], performance: { impressions: 28500, clicks: 2340, shares: 387, conversions: 78 } },
    { title: 'Case Study: How Virtual Staging Increased Sale Prices by 15%', body: 'See how a 200-unit Amsterdam waterfront development used AI-powered virtual staging to create aspirational interiors and accelerate buyer decisions.', content_type: 'case_study', channels: ['email', 'linkedin', 'blog'], status: 'published', tags: ['case-study', 'virtual-staging', 'ROI'] },
    { title: 'The Rise of Sustainable Luxury: Green Building Trends Reshaping Real Estate', body: 'How BREEAM and LEED certifications are becoming must-haves for premium developments, and why buyers are willing to pay a 12% premium for sustainable properties.', content_type: 'blog_post', channels: ['blog', 'linkedin'], status: 'published', tags: ['sustainability', 'green-building', 'trends'], performance: { impressions: 19200, clicks: 1680, shares: 298, conversions: 45 } },
    { title: 'Smart Home Technology: The New Standard in Premium Real Estate', body: 'From automated climate control and integrated security to voice-activated concierge services, smart home features are now table stakes for luxury buyers.', content_type: 'blog_post', channels: ['blog', 'linkedin', 'instagram'], status: 'published', tags: ['smart-home', 'proptech', 'innovation'], performance: { impressions: 31000, clicks: 2780, shares: 445, conversions: 62 } },
    { title: 'Webinar: AI-Powered Property Valuation — Accuracy Meets Speed', body: 'Join our chief data scientist as she demonstrates how machine learning models trained on 500K+ transactions deliver valuations within 3% of final sale price.', content_type: 'webinar', channels: ['email', 'linkedin', 'facebook'], status: 'published', tags: ['webinar', 'AI', 'valuation'] },
    { title: 'Infographic: The Anatomy of a Perfect Property Listing', body: 'Visual guide showing how professional photography, drone footage, 3D tours, and AI-optimized descriptions increase listing engagement by up to 240%.', content_type: 'infographic', channels: ['linkedin', 'instagram', 'twitter'], status: 'published', tags: ['infographic', 'listings', 'best-practices'], performance: { impressions: 47500, clicks: 4120, shares: 890, conversions: 56 } },
    { title: 'The Complete Guide to Cross-Border Property Investment in the EU', body: 'Navigate tax implications, residency permits, financing options, and legal frameworks for purchasing property across European jurisdictions.', content_type: 'guide', channels: ['email', 'blog'], status: 'published', tags: ['cross-border', 'investment', 'legal'], performance: { impressions: 15800, clicks: 1920, shares: 234, conversions: 98 } },
    { title: 'Video: 360-Degree Virtual Tour — Canal District Penthouse Collection', body: 'Experience five exclusive penthouse residences through our immersive virtual tour platform, complete with neighbourhood walk-throughs and sunset terrace views.', content_type: 'video', channels: ['youtube', 'linkedin', 'instagram'], status: 'published', tags: ['video', 'virtual-tour', 'showcase'] },
    { title: 'How PropTech is Disrupting Traditional Real Estate Brokerage', body: 'Analysis of how technology-first platforms are transforming buyer experiences, reducing transaction times by 60%, and reshaping commission structures.', content_type: 'blog_post', channels: ['blog', 'linkedin'], status: 'scheduled', tags: ['proptech', 'disruption', 'industry-trends'] },
    { title: 'LinkedIn Carousel: 5 Signs a Neighbourhood is About to Surge in Value', body: 'Visual guide covering infrastructure investment signals, permit data analysis, demographic shifts, transit connectivity, and commercial tenant mix.', content_type: 'carousel', channels: ['linkedin'], status: 'published', tags: ['carousel', 'investment', 'neighbourhood-analysis'], performance: { impressions: 38000, clicks: 3200, shares: 567, conversions: 41 } },
    { title: 'Email: Monthly Prestige Market Pulse', body: 'Curated monthly newsletter featuring premium listing highlights, market movement analysis, investment opportunities, and upcoming exclusive events.', content_type: 'newsletter', channels: ['email'], status: 'published', tags: ['newsletter', 'monthly', 'market-pulse'] },
    { title: 'Social Post: MIPIM Cannes 2026 Preview', body: 'Join Prestige Properties at MIPIM Cannes 2026. Visit our waterfront pavilion for exclusive investment presentations, virtual tour demos, and networking with Europe\'s leading developers.', content_type: 'social_post', channels: ['linkedin', 'twitter', 'instagram'], status: 'scheduled', tags: ['event', 'MIPIM', 'announcement'] },
    { title: 'Podcast: Property Leaders — Episode 8: The Future of Urban Living', body: 'In-depth conversation with Willem van Dijk on mixed-use development, the 15-minute city concept, and how Amsterdam is redefining urban luxury.', content_type: 'podcast', channels: ['spotify', 'linkedin', 'email'], status: 'draft', tags: ['podcast', 'interview', 'urban-development'] },
    { title: 'ROI Calculator: Property Investment Returns Simulator', body: 'Interactive tool allowing investors to model rental yields, capital appreciation, tax implications, and total returns across European markets.', content_type: 'interactive', channels: ['email', 'linkedin'], status: 'published', tags: ['ROI', 'calculator', 'lead-magnet'] },
  ],

  competitors: [
    { name: 'LuxeLiving Digital', description: 'Venture-backed PropTech startup focused on luxury property marketplace and AI matching', website: 'luxelivingdigital.com', market_share: 22, strengths: ['Strong brand recognition', 'Large luxury listing inventory', 'Excellent mobile app'], weaknesses: ['Limited European coverage', 'No property management features', 'High commission structure'] },
    { name: 'PropVision', description: 'Established property technology platform specializing in 3D visualization and virtual tours', website: 'propvision.eu', market_share: 18, strengths: ['Best-in-class 3D rendering', 'Strong developer partnerships', 'Multi-language platform'], weaknesses: ['No investment analytics', 'Basic CRM features', 'Slow feature releases'] },
    { name: 'HomeConnect Pro', description: 'Mid-market property management and tenant engagement platform expanding into premium segment', website: 'homeconnectpro.com', market_share: 15, strengths: ['Comprehensive property management', 'Strong tenant portal', 'Competitive pricing'], weaknesses: ['Not positioned for luxury market', 'Limited virtual tour capabilities', 'Weak analytics'] },
    { name: 'EstateIQ', description: 'Data-driven real estate analytics platform providing market intelligence and valuation tools', website: 'estateiq.io', market_share: 10, strengths: ['Superior data analytics', 'Accurate market predictions', 'API-first architecture'], weaknesses: ['No listing management', 'Developer-focused UX', 'Small sales team in Europe'] },
  ],

  events: [
    { name: 'MIPIM Cannes 2026', type: 'conference', description: 'The world\'s leading property market conference bringing together 26,000+ real estate professionals', location: 'Palais des Festivals', city: 'Cannes', country: 'France', date_start: daysFromNow(20), date_end: daysFromNow(23), expected_attendees: 26000, target_audience_match: 95, estimated_roi: 580, estimated_leads: 120, networking_value: 98, cost: 75000, topics: ['Investment', 'Urban Development', 'PropTech', 'Sustainability', 'Luxury Residential'], status: 'confirmed', priority_score: 99 },
    { name: 'PropTech Summit Amsterdam', type: 'summit', description: 'Premier European summit for property technology innovation and digital transformation in real estate', location: 'Johan Cruijff ArenA', city: 'Amsterdam', country: 'Netherlands', date_start: daysFromNow(50), date_end: daysFromNow(51), expected_attendees: 3500, target_audience_match: 90, estimated_roi: 420, estimated_leads: 65, networking_value: 92, cost: 18000, topics: ['PropTech Innovation', 'AI in Real Estate', 'Digital Transactions', 'Smart Buildings'], status: 'confirmed', priority_score: 91 },
    { name: 'Luxury Property Show London', type: 'exhibition', description: 'Exclusive showcase for ultra-premium residential properties attracting global high-net-worth buyers and investors', location: 'Olympia London', city: 'London', country: 'United Kingdom', date_start: daysFromNow(75), date_end: daysFromNow(77), expected_attendees: 8000, target_audience_match: 88, estimated_roi: 350, estimated_leads: 45, networking_value: 85, cost: 32000, topics: ['Luxury Residential', 'International Investment', 'Architecture', 'Interior Design'], status: 'evaluating', priority_score: 82 },
  ],

  personas: [
    { name: 'Henrik — The Institutional Investor', description: 'Senior investment professional managing a real estate portfolio for a pension fund or family office, seeking stable yields and capital preservation', demographics: { age: '45-58', education: 'MBA / CFA / Real Estate Finance', income: '€250K-€400K', location: 'Major European financial centre' }, psychographics: { motivation: 'Maximize risk-adjusted returns across diversified property portfolio', decision_style: 'Data-driven, risk-averse, consensus with investment committee', risk_tolerance: 'Moderate — requires comprehensive due diligence and proven track record' }, pain_points: ['Lack of transparency in off-market deals', 'Slow and opaque transaction processes', 'Difficulty comparing cross-border yields', 'ESG reporting requirements'], goals: ['Achieve 7%+ net yield across portfolio', 'Diversify into 3 new European markets', 'Full ESG compliance by 2027'], preferred_channels: ['Email', 'Private events', 'Industry conferences', 'Personal introductions'] },
    { name: 'Sophie — The Luxury Home Buyer', description: 'High-net-worth individual seeking a premium primary residence or vacation property, values lifestyle and exclusivity', demographics: { age: '38-52', education: 'University degree, often entrepreneurial background', income: '€500K+', location: 'Amsterdam, London, Paris, or Zurich' }, psychographics: { motivation: 'Find a distinctive property that reflects personal success and lifestyle aspirations', decision_style: 'Emotionally driven but needs reassurance from market data', risk_tolerance: 'Low for primary residence — seeks established, prime locations' }, pain_points: ['Time-poor, needs curated shortlists not endless browsing', 'Privacy concerns during property search', 'Difficulty visualising renovation potential', 'Navigating foreign purchase regulations'], goals: ['Find the perfect waterfront or penthouse property', 'Complete purchase within 6 months', 'Seamless relocation support'], preferred_channels: ['Private viewings', 'Instagram', 'Referrals from personal network', 'Luxury lifestyle publications'] },
    { name: 'Marco — The Property Developer', description: 'Experienced developer sourcing land, managing construction, and marketing residential or mixed-use projects', demographics: { age: '40-55', education: 'Civil Engineering / Architecture / Business', income: '€180K-€300K', location: 'Urban centres across Western Europe' }, psychographics: { motivation: 'Deliver projects on time and above projected margins while building brand reputation', decision_style: 'Pragmatic, relationship-oriented, values proven technology', risk_tolerance: 'High on development risk but low on technology risk — needs reliable platforms' }, pain_points: ['Pre-sales velocity in competitive markets', 'Rising construction and material costs', 'Regulatory complexity across jurisdictions', 'Buyer engagement during construction phase'], goals: ['Achieve 85%+ pre-sales before construction completion', 'Reduce marketing cost per unit by 30%', 'Digital-first buyer experience across all projects'], preferred_channels: ['LinkedIn', 'Industry events', 'Direct sales team contact', 'Trade publications'] },
  ],

  products: [
    { name: 'Prestige Portfolio Platform', description: 'End-to-end property marketing and sales platform with AI-powered listings, virtual tours, buyer matching, and transaction management for premium real estate', category: 'Platform', status: 'active', price_range: '€60K-€250K/year', target_audience: 'Developers and brokerages with 50+ premium listings', key_features: ['AI property matching', '3D virtual tours', 'Digital transaction management', 'Buyer analytics dashboard', 'Multi-language listings'], competitive_advantages: ['97% valuation accuracy', '60% faster time-to-sale', 'White-label customization', '240% higher listing engagement'] },
    { name: 'Prestige Virtual Stage', description: 'AI-powered virtual staging and 3D visualization tool that transforms empty spaces into aspirational interiors tailored to target buyer demographics', category: 'Module', status: 'active', price_range: '€15K-€60K/year', target_audience: 'Property developers and estate agents', key_features: ['AI interior design generation', 'Demographic-targeted staging', 'Before/after comparisons', 'Integration with listing platforms'], competitive_advantages: ['15% average increase in sale price', '40+ design styles', 'Renders in under 60 seconds', 'Proven ROI across 1,200+ projects'] },
    { name: 'Prestige Investor Intelligence', description: 'Advanced property investment analytics platform providing market forecasting, yield modelling, portfolio optimization, and ESG risk scoring', category: 'Add-on', status: 'active', price_range: '€25K-€90K/year', target_audience: 'Institutional investors and fund managers', key_features: ['Market forecasting engine', 'Yield scenario modelling', 'Portfolio risk analysis', 'ESG compliance scoring', 'Cross-border tax simulator'], competitive_advantages: ['500K+ transaction training dataset', 'Covers 15 European markets', '94% forecast accuracy', 'Regulatory reporting automation'] },
  ],

  strategicObjectives: [
    { name: 'European Market Expansion', description: 'Expand active market coverage from 8 to 15 European cities by end of 2026', category: 'growth', target_value: 15, current_value: 8, unit: 'markets', priority: 'critical' },
    { name: 'Platform Revenue Target', description: 'Achieve EUR 18M in platform subscription revenue by year-end 2026', category: 'revenue', target_value: 18000000, current_value: 11200000, unit: 'EUR', priority: 'critical' },
    { name: 'Virtual Tour Adoption', description: 'Reach 5,000 properties with active 3D virtual tours on the platform', category: 'product', target_value: 5000, current_value: 3200, unit: 'active_tours', priority: 'high' },
    { name: 'Client Satisfaction Excellence', description: 'Maintain NPS score above 75 across all product lines', category: 'customer_success', target_value: 75, current_value: 78, unit: 'NPS', priority: 'high' },
  ],

  organizationEntities: [
    { name: 'Product & Technology', type: 'department', description: 'Platform engineering, AI/ML development, 3D rendering, and PropTech innovation' },
    { name: 'Sales & Partnerships', type: 'department', description: 'Enterprise sales, broker partnerships, developer relations, and international expansion' },
    { name: 'Marketing & Brand', type: 'department', description: 'Brand strategy, content creation, demand generation, events, and luxury market positioning' },
    { name: 'Property Operations', type: 'department', description: 'Property onboarding, virtual tour production, listing quality assurance, and client success' },
    { name: 'Investment Advisory', type: 'advisory', description: 'External panel of real estate investors and market analysts guiding product strategy and market intelligence' },
  ],

  // Finance data
  financeCustomers: [
    { name: 'Amsterdam Development Group', email: 'finance@amsterdamdevelopment.nl', phone: '+31 20 535 8800', address: 'Herengracht 450', city: 'Amsterdam', postal_code: '1017 CA', country: 'Netherlands', contact_person: 'Willem van Dijk', kvk_number: '34891256', btw_number: 'NL812345678B01', payment_terms: 30, status: 'active' },
    { name: 'Bouwfonds Investment Partners', email: 'accounts@bouwfondspartners.nl', phone: '+31 30 219 5000', address: 'Stationsplein 65', city: 'Utrecht', postal_code: '3511 ED', country: 'Netherlands', contact_person: 'Charlotte de Graaf', kvk_number: '45123890', btw_number: 'NL823456789B01', payment_terms: 45, status: 'active' },
    { name: 'Engel & Schneider Immobilien', email: 'buchhaltung@engelvolk-munich.de', phone: '+49 89 998 8880', address: 'Maximilianstrasse 35', city: 'Munich', postal_code: '80539', country: 'Germany', contact_person: 'Maximilian Schneider', kvk_number: '', btw_number: 'DE234567891', payment_terms: 30, status: 'active' },
    { name: 'Nordic Property Capital', email: 'finance@nordicproperty.se', phone: '+46 8 505 123 00', address: 'Strandv\u00e4gen 7A', city: 'Stockholm', postal_code: '114 56', country: 'Sweden', contact_person: 'Sofia Lindqvist', kvk_number: '', btw_number: 'SE556789012301', payment_terms: 30, status: 'active' },
    { name: 'Paris Luxury Residences', email: 'comptabilite@parisresidences.fr', phone: '+33 1 44 51 8800', address: 'Avenue Montaigne 42', city: 'Paris', postal_code: '75008', country: 'France', contact_person: 'Jean-Pierre Moreau', kvk_number: '', btw_number: 'FR12345678901', payment_terms: 45, status: 'active' },
    { name: 'Green Urban Developments', email: 'finance@greenurban.nl', phone: '+31 20 820 3400', address: 'Zuidas Boulevard 100', city: 'Amsterdam', postal_code: '1082 MD', country: 'Netherlands', contact_person: 'Emma van Houten', kvk_number: '56234789', btw_number: 'NL834567890B01', payment_terms: 30, status: 'active' },
    { name: 'London Estate Group', email: 'accounts@londonestategroup.uk', phone: '+44 20 7946 0958', address: '1 Mayfair Place', city: 'London', postal_code: 'W1J 8AJ', country: 'United Kingdom', contact_person: 'Victoria Blackwell', kvk_number: '', btw_number: 'GB987654321', payment_terms: 60, status: 'active' },
    { name: 'Milano Prime Realty', email: 'amministrazione@milanoprime.it', phone: '+39 02 7600 8900', address: 'Via Montenapoleone 18', city: 'Milan', postal_code: '20121', country: 'Italy', contact_person: 'Isabella Romano', kvk_number: '', btw_number: 'IT12345678901', payment_terms: 30, status: 'active' },
  ],

  financeSuppliers: [
    { name: 'Matterport Europe', email: 'billing@matterport.eu', phone: '+44 20 3870 1200', address: 'Tech Hub, 20 Ropemaker St', city: 'London', postal_code: 'EC2Y 9AR', country: 'United Kingdom', contact_person: 'Enterprise Accounts', kvk_number: '', btw_number: 'GB112233445', payment_terms: 30, status: 'active' },
    { name: 'PropertyAds Agency', email: 'invoices@propertyads.nl', phone: '+31 20 555 0340', address: 'Keizersgracht 520', city: 'Amsterdam', postal_code: '1017 EK', country: 'Netherlands', contact_person: 'Daan Vermeer', kvk_number: '67234501', btw_number: 'NL456123789B01', payment_terms: 14, status: 'active' },
    { name: 'AWS Cloud Services', email: 'aws-billing@amazon.com', phone: '+1 206 922 0880', address: '410 Terry Avenue North', city: 'Seattle', postal_code: '98109', country: 'USA', contact_person: 'Cloud Solutions Team', kvk_number: '', btw_number: 'US876543210', payment_terms: 30, status: 'active' },
    { name: 'Kadaster Data Solutions', email: 'data@kadaster.nl', phone: '+31 88 183 2200', address: 'Hofstraat 110', city: 'Apeldoorn', postal_code: '7311 KZ', country: 'Netherlands', contact_person: 'Data Services', kvk_number: '09116957', btw_number: 'NL001174845B01', payment_terms: 15, status: 'active' },
    { name: 'LuxeContent Studio', email: 'finance@luxecontent.eu', phone: '+31 20 261 0500', address: 'NDSM-Plein 28', city: 'Amsterdam', postal_code: '1033 WB', country: 'Netherlands', contact_person: 'Creative Director', kvk_number: '78345612', btw_number: 'NL567890234B01', payment_terms: 14, status: 'active' },
  ],

  financeInvoices: [
    { invoice_type: 'sales', entity_name: 'Amsterdam Development Group', description: 'Prestige Portfolio Platform — Annual Enterprise License 2026', subtotal: 185000, tax_amount: 38850, total_amount: 223850, status: 'paid', days_offset: -55 },
    { invoice_type: 'sales', entity_name: 'Bouwfonds Investment Partners', description: 'Prestige Investor Intelligence — Annual License + Onboarding', subtotal: 92000, tax_amount: 19320, total_amount: 111320, status: 'paid', days_offset: -40 },
    { invoice_type: 'sales', entity_name: 'Nordic Property Capital', description: 'Prestige Portfolio Platform — Multi-Market License', subtotal: 145000, tax_amount: 30450, total_amount: 175450, status: 'pending', days_offset: -12 },
    { invoice_type: 'sales', entity_name: 'Engel & Schneider Immobilien', description: 'Prestige Virtual Stage — Annual License + Integration', subtotal: 48000, tax_amount: 9120, total_amount: 57120, status: 'paid', days_offset: -80 },
    { invoice_type: 'sales', entity_name: 'Paris Luxury Residences', description: 'Prestige Portfolio Platform — Premium Tier License', subtotal: 125000, tax_amount: 26250, total_amount: 151250, status: 'pending', days_offset: -8 },
    { invoice_type: 'sales', entity_name: 'Green Urban Developments', description: 'Prestige Virtual Stage — Project License (200 units)', subtotal: 35000, tax_amount: 7350, total_amount: 42350, status: 'overdue', days_offset: -70 },
    { invoice_type: 'sales', entity_name: 'London Estate Group', description: 'Consulting — International Expansion Strategy & Platform Setup', subtotal: 65000, tax_amount: 13650, total_amount: 78650, status: 'paid', days_offset: -35 },
    { invoice_type: 'sales', entity_name: 'Milano Prime Realty', description: 'Prestige Investor Intelligence — Quarterly Subscription', subtotal: 22500, tax_amount: 4725, total_amount: 27225, status: 'pending', days_offset: -5 },
    { invoice_type: 'purchase', entity_name: 'AWS Cloud Services', description: 'Cloud Infrastructure — Platform Hosting & CDN Q1 2026', subtotal: 28500, tax_amount: 5985, total_amount: 34485, status: 'paid', days_offset: -30 },
    { invoice_type: 'purchase', entity_name: 'Matterport Europe', description: '3D Capture SDK License — Enterprise Tier Annual', subtotal: 42000, tax_amount: 8820, total_amount: 50820, status: 'paid', days_offset: -50 },
    { invoice_type: 'purchase', entity_name: 'PropertyAds Agency', description: 'MIPIM Cannes 2026 Campaign Design & Media Production', subtotal: 38000, tax_amount: 7980, total_amount: 45980, status: 'pending', days_offset: -14 },
    { invoice_type: 'purchase', entity_name: 'Kadaster Data Solutions', description: 'Property Registry API Access — Annual Data Feed License', subtotal: 18500, tax_amount: 3885, total_amount: 22385, status: 'paid', days_offset: -25 },
    { invoice_type: 'purchase', entity_name: 'LuxeContent Studio', description: 'Luxury Property Photography & Drone Footage — Q1 Productions', subtotal: 24000, tax_amount: 5040, total_amount: 29040, status: 'paid', days_offset: -60 },
    { invoice_type: 'sales', entity_name: 'Amsterdam Development Group', description: 'Prestige Virtual Stage — Canal District Launch Add-on', subtotal: 55000, tax_amount: 11550, total_amount: 66550, status: 'draft', days_offset: 0 },
    { invoice_type: 'purchase', entity_name: 'AWS Cloud Services', description: 'Cloud Infrastructure — Platform Hosting & CDN Q2 2026', subtotal: 31200, tax_amount: 6552, total_amount: 37752, status: 'draft', days_offset: 0 },
  ],

  financeBudgets: [
    { category: 'Cloud Infrastructure & PropTech', budgeted_amount: 150000, actual_amount: 112000 },
    { category: 'Marketing & Events', budgeted_amount: 280000, actual_amount: 195000 },
    { category: 'Research & Development', budgeted_amount: 420000, actual_amount: 310000 },
    { category: 'Personnel & Recruitment', budgeted_amount: 1200000, actual_amount: 890000 },
    { category: 'Property Content Production', budgeted_amount: 180000, actual_amount: 125000 },
    { category: 'Sales & Business Development', budgeted_amount: 160000, actual_amount: 108000 },
  ],

  financeGoals: [
    { goal: 'Achieve EUR 18M platform revenue', category: 'revenue', target_value: 18000000, current_value: 11200000, unit: 'EUR', status: 'on_track' },
    { goal: 'Maintain gross margin above 72%', category: 'profitability', target_value: 72, current_value: 76, unit: '%', status: 'achieved' },
    { goal: 'Reduce customer acquisition cost by 25%', category: 'efficiency', target_value: 25, current_value: 18, unit: '%', status: 'on_track' },
    { goal: 'Secure Series B funding of EUR 20M', category: 'funding', target_value: 20000000, current_value: 0, unit: 'EUR', status: 'in_progress' },
  ],

  yearPlanName: 'Prestige Properties \u2014 Financial Plan 2026',
};
